export const NAMING: string[][] = [
  [
    "Trust Kernel",
    "none (canonical)",
    "Governance layer — constitutional enforcement core",
    "Deterministic risk classification, default-deny, autonomy-ceiling checks, HIGH/CRITICAL human-gate. Not a second governance system.",
    "Governance layer",
    "Called before Governance Engine evaluation. Does not issue tokens, grants, or execute.",
  ],
  [
    "Governance Engine",
    "Policy Engine (alias)",
    "Governance layer — runtime",
    "Evaluate versioned policy against a classified proposal. Produce allow/deny. Cannot classify risk (Trust Kernel does).",
    "Governance layer",
    "Consumes Trust Kernel class. Feeds Authority System.",
  ],
  [
    "Authority System",
    "Authority Kernel (alias, retired in v5.3 prose)",
    "Authority layer — runtime",
    "Issue, delegate, revoke authority grants. Reject self-grants.",
    "Authority layer",
    "Does not classify risk. Does not mint capability tokens.",
  ],
  [
    "Capability System",
    "Capability Manager (alias, retired in v5.3 prose)",
    "Capabilities layer — runtime",
    "Mint, validate, expire, revoke capability tokens. Tokens are not transferable authority.",
    "Capabilities layer",
    "Requires a live Authority grant. Consumed by Execution Broker.",
  ],
  [
    "Execution Broker",
    "none",
    "Execution layer — admit/deny",
    "Only admission point for execution. Binds proposal + token + Isolation Guard.",
    "Execution layer",
    "Never executes on the host. Spawns a Worker in a sandbox.",
  ],
  [
    "Isolation Guard",
    "none",
    "Execution layer — boundary enforcer",
    "Bind worker to tenant, product, environment. Deny cross-boundary FS/network/secret access.",
    "Execution layer",
    "Consulted by Broker before spawn; enforced inside the sandbox.",
  ],
  [
    "Worker",
    "Execution identity",
    "Execution layer — ephemeral identity",
    "Runs the admitted action inside the sandbox. Cannot propose, approve, or verify.",
    "Execution layer",
    "Spawned per proposal. Destroyed after extract. Distinct from Agent Identity.",
  ],
  [
    "Verification Engine",
    "none",
    "Verification layer — runtime",
    "Independent verification of results. Writes Evidence Envelopes. Never implements product work.",
    "Verification layer",
    "Verifier identity ≠ worker identity ≠ proposing agent identity for the same work.",
  ],
  [
    "Evidence Store",
    "none",
    "Evidence layer — runtime",
    "Store Evidence Envelopes. E0 is a defect, not a level that can be stored as success.",
    "Evidence layer",
    "Append-oriented. Promotion of claims requires a stored envelope.",
  ],
  [
    "Audit System",
    "none",
    "Audit layer — runtime",
    "Append-only AuditEvent write path. Hash chain plus write-control.",
    "Audit layer",
    "Agents and workers cannot update or delete. System + Trust Kernel + Recovery (authorized) may append.",
  ],
  [
    "Recovery System",
    "none",
    "Constitutional subsystem (not an ops feature)",
    "Freeze, rollback, restore. Authority is Human. Evidence and audit are mandatory.",
    "Human + Constitution, implemented as Recovery System",
    "Unaudited recovery is rejected. Not owned by Operations System.",
  ],
  [
    "Intelligence Contract",
    "Provider adapter (behind the contract)",
    "Intelligence layer",
    "Only path to models. Outputs are proposals. Adapters are replaceable.",
    "Intelligence layer",
    "Core must not import vendor SDKs.",
  ],
  [
    "Product Factory",
    "none",
    "Factory subsystem across Planning + Execution + Verification",
    "Idea through retirement under the authoritative lifecycle.",
    "Planning layer owns plans; Execution owns runs",
    "A plan is not a deploy.",
  ],
  [
    "Operations System",
    "none",
    "TARGET_ARCHITECTURE for full ITSM; thin operator views in Day 30",
    "Monitoring, incident, compliance views.",
    "Operations",
    "Does not own Recovery. Does not grant authority.",
  ],
];

export const IDENTITY_RIGHTS: string[][] = [
  ["Human", "No (except freeze/approve records)", "Yes", "Yes", "No (not as Worker)", "May confirm CRITICAL", "Yes", "Yes", "Yes", "Yes", "Yes"],
  ["Agent (advise A0)", "Yes — recommendation", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
  ["Agent (propose A1)", "Yes — AgentProposal", "No", "No", "No", "No", "No", "Append only via system", "Recommend only", "No", "No"],
  ["Agent (verify A2, duty=verify)", "No for implementation", "No", "No", "No implementation", "Yes — others' work only", "Yes (envelope)", "Append via system", "No", "No", "No"],
  ["Worker", "No", "No", "No", "Yes — in sandbox only", "No", "No", "No", "No", "No", "No"],
  ["Tenant", "Scope, not an actor", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
  ["Product", "Scope, not an actor", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
  ["Environment", "Bound, not an actor", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
  ["System (Trust Kernel, Audit, Recovery runtime)", "No proposals", "No", "Enforces", "No product exec", "No", "May emit system evidence", "Yes — append", "No", "Executes freeze when Human ordered", "Executes restore when Human ordered"],
];
