export const CATALOGUE: string[][] = [
  ["AG-DISC", "Product Discovery", "Factory", "A1", "propose", "Discovery proposals", "None", "None — cannot verify own discovery", "Cannot execute", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-REQ", "Requirements", "Factory", "A1", "propose", "Requirements proposals", "None", "None", "Cannot execute", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-DOM", "Domain Analyst", "Factory", "A1", "propose", "Domain-model proposals", "None", "None", "Cannot write production schema", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-ARCH", "Architecture", "Factory", "A1", "propose", "Architecture proposals", "None", "None", "Cannot implement without human approval", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-DB", "Database", "Factory", "A1", "propose", "Schema/migration proposals", "None", "None", "Production apply only via Broker after approval", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-UX", "UX", "Factory", "A1", "propose", "UX proposals", "None", "None", "Cannot ship UI", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-SEC", "Security", "Security engineering", "A1", "propose", "Findings, threat models, revocation recommendations", "None", "FORBIDDEN on own remediations (Article 8)", "Cannot change production silently", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-SECV", "Security Verifier", "Security verification", "A2", "verify", "Independent security verification of others' work", "None", "Yes — never of AG-SEC work it originated; never of own prior proposal (it does not propose)", "No implementation execution", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-REPO", "Repository", "Factory", "A1", "propose", "Repo-change proposals; Brokered patches when tokenled", "None", "None", "No direct production, no broker bypass", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-QA", "QA", "Quality", "A1", "propose", "Test designs; governed test runs are not independent verification", "None", "FORBIDDEN as independent verifier of tests it designed or ran", "No promotion of unverified work", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-VER", "Verification", "Verification", "A2", "verify", "Independent verification; Evidence Envelopes; gate records", "None", "Yes — never of work this identity performed", "No product implementation execution. A2 here is governed verification duty, not execution duty.", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-DEP", "Deployment", "Release", "A1", "propose", "Deployment proposals", "None", "None", "No agent deploys; Human/Broker path only", "product+environment", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-OPS", "Operations", "Operations", "A1", "propose", "Incident and ops proposals", "None", "None", "Does not own Recovery", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-FIN", "Financial Intelligence", "Intelligence", "A0", "advise", "Cost recommendations as proposals", "None", "None", "None", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-LEG", "Legal/Compliance Intelligence", "Intelligence", "A0", "advise", "Compliance gap proposals", "None", "None", "None", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-RSH", "Research Intelligence", "Intelligence", "A0", "advise", "Research notes as proposals", "None", "None", "None", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-PERF", "Performance Intelligence", "Intelligence", "A0", "advise", "Performance notes as proposals", "None", "None", "None", "product", "SPECIFIED — NOT IMPLEMENTED"],
  ["AG-REL", "Reliability Intelligence", "Intelligence", "A0", "advise", "Reliability notes as proposals", "None", "None", "None", "product", "SPECIFIED — NOT IMPLEMENTED"],
];
