import type { Block, Section } from "./types";

function s(
  id: string,
  num: string,
  nav: string,
  title: string,
  dek: string,
  v2: Block[],
): Section {
  return {
    id,
    part: "Constitution",
    partId: "A",
    num,
    nav,
    title,
    dek,
    v1: [
      {
        k: "callout",
        tone: "note",
        title: "Phase 5 Article 5 deep draft is not in the received freeze",
        t: "Compact Article 5 in A.3 remains the short form. Articles 1–4 are LOCKED. Switch to the operative issue.",
      },
    ],
    v2,
  };
}

export const PHASE5_A5: Section[] = [
  s(
    "ph5",
    "VIII.0",
    "Phase 5",
    "Phase 5 — Article 5 lock record",
    "LOCKED — HUMAN ACCEPTED. Compact A.3 unchanged. Phase 6 closed.",
    [
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Constitutional artifact: Article 5 — Capability Is Scoped. Version: v5.3 (no v5.4). Status: LOCKED — HUMAN ACCEPTED. Compact A.3 unchanged. Articles 1–4 unchanged. ATK-5-01–50 accepted/blocked. INV-5-01–30 accepted. Runtime: SPECIFIED — ENFORCEMENT PENDING. Implementation: NOT CLAIMED COMPLETE. Phase 6 — Article 6: CLOSED / NOT AUTHORIZED.",
      },
      {
        k: "table",
        cols: ["Phase", "Article", "Status"],
        rows: [
          ["Phase 1–4", "Articles 1–4", "LOCKED / HUMAN ACCEPTED — UNCHANGED"],
          ["Phase 5", "Article 5", "LOCKED / HUMAN ACCEPTED"],
          ["Phase 6", "Article 6", "CLOSED / NOT AUTHORIZED"],
        ],
      },
    ],
  ),

  s(
    "a5law",
    "VIII",
    "Art. 5 Law",
    "Article 5 — Capability Is Scoped (law)",
    "Possessing the technical ability to act is not authority to act. LOCKED — HUMAN ACCEPTED.",
    [
      {
        k: "callout",
        tone: "note",
        title: "A.3 compact form — not replaced",
        t: "A.3 Article 5 remains Capability Is Scoped. This draft states the boundary Article 4 handed over: a token is not sovereignty; capability cannot exceed or become the authority chain. Do not silently retitle Compact A.3.",
      },
      { k: "h", t: "5.1 Purpose", l: 2 },
      {
        k: "p",
        t: "Article 5 prevents any technical capability, credential, token, execution permission, tool access, runtime privilege, agent or worker capability, or system permission from substituting for constitutional authority (Articles 1–4). Capability may enable execution. Authority determines whether execution is lawfully admitted. Technical possibility must never silently become constitutional permission.",
      },
      { k: "h", t: "5.2 Constitutional rule", l: 2 },
      {
        k: "p",
        t: "No technical capability, credential, token, permission, tool access, runtime privilege, provider permission, or execution mechanism constitutes constitutional authority by itself. An actor may execute a consequential action only if (i) a valid Article 4 authority chain exists, (ii) a lawful capability is issued within that chain and does not exceed it, (iii) the requested act matches both chain and capability, and (iv) the Trust Kernel and Broker admit. If capability is missing, expired, revoked, out of scope, or greater than the enabling authority: DENY / DO NOT EXECUTE. Mismatch is not silently reduced or repaired.",
      },
      { k: "h", t: "5.3 Distinctions (must not collapse)", l: 2 },
      {
        k: "table",
        cols: ["Term", "Meaning in Article 5"],
        rows: [
          ["Authority / Authority Grant", "Lawful permission origin and issued grant (Arts. 1–4). Not a token."],
          ["Capability / capability grant", "Bounded technical means of execution derived from a grant. Not authority."],
          ["Token / CapabilityToken", "Representation of a capability. Cryptographic validity ≠ constitutional authority."],
          ["Credential / secret possession", "Identity or secret material. Not authority."],
          ["Permission / tool / API / network / filesystem access", "Technical reach. Not AGBOFA authority."],
          ["Runtime / OS / sandbox / infrastructure privilege", "Host or container power. Not a grant."],
          ["Execution right", "Broker admit of this act. Not a standing sovereign right."],
          ["Agent / worker / service identity capability", "Catalogued or minted means. Worker ≠ grantor."],
          ["Provider permission", "External accept. Not AGBOFA authority (Art. 2)."],
        ],
      },
      { k: "h", t: "5.4 Lawful capability", l: 2 },
      {
        k: "p",
        t: "A lawful capability is a bounded technical means: subject (human/agent/worker/service), tenant, product, environment, action, resource, risk class not above the chain, duration, constraints, provenance (issuing Authority Grant id), issuance by the Capability System, activation, expiry, revocation, auditability. Database field layout is implementation. Constitutionally necessary: subject, tenant, product, environment, action, resource where applicable, risk bound, duration, grant provenance, expiry, revocability. Delegation of capability is not a second authority path (5.10).",
      },
      { k: "h", t: "5.5 Authority → capability (one way)", l: 2 },
      {
        k: "flow",
        steps: [
          "Human / constitutional source",
          "Authority System issues Authority Grant",
          "Bounded Article 4 chain",
          "Capability System issues capability / token ≤ grant",
          "Broker + Guard admit matching request",
          "Worker executes (claim)",
          "Audit",
        ],
      },
      {
        k: "p",
        t: "Forbidden inversions: capability → authority; credential → authority; token → authority; tool access → authority; root → authority; provider permission → authority. Direction is not reversible. Capability System does not originate Human Authority.",
      },
      { k: "h", t: "5.6 Capability floor", l: 2 },
      {
        k: "p",
        t: "Effective Capability ≤ Authorized Authority Scope. A capability must not authorize a broader resource, action, tenant, product, environment, duration, higher risk class, or different subject/agent/worker than the chain permits. If capability exceeds authority: DENY. Do not silently clip, reinterpret, or repair.",
      },
    ],
  ),

  s(
    "a5tok",
    "VIII.C",
    "Art. 5 Chain",
    "Article 5 — tokens, gate, revocation, transfer, offline",
    "Token ≠ sovereignty. Oversize = DENY. SPECIFIED — ENFORCEMENT PENDING.",
    [
      { k: "h", t: "5.7 Token rules", l: 2 },
      {
        k: "p",
        t: "A CapabilityToken represents bounded permission. It does not create sovereignty; cannot exceed originating authority; cannot extend duration or expand scope; cannot lower the risk floor; cannot authorize a prohibited action; cannot survive revocation of its grant; cannot become authority because it is cryptographically valid; cannot manufacture a Human Authority source. Compact: tokens required for execution; short-lived; renewable only through governance.",
      },
      {
        k: "p",
        t: "Token must bind: subject, audience/use, tenant, product, environment, action, resource where applicable, expiry, issuance provenance (grant id), revocation status. Replay, theft, tamper, reuse outside tuple, unbound exchange, and minting outside the Capability System are deny. Cryptographic validity proves mechanism integrity, not constitutional authority.",
      },
      { k: "h", t: "5.8 Token oversize / amplification (mandatory)", l: 2 },
      {
        k: "p",
        t: "A valid grant must not produce a token whose effective permissions exceed the grant. Resource A → token A+B: DENY. LOW → HIGH: DENY. Development → production: DENY. Tenant A → A+B: DENY. Action X → X+Y: DENY. No token may amplify authority. Detect at mint and at admit.",
      },
      { k: "h", t: "5.9 Execution gate", l: 2 },
      {
        k: "ol",
        items: [
          "Authority chain exists, valid, current, in scope (Art. 4).",
          "Capability derived/admitted within that authority, ≤ grant.",
          "Requested action matches both authority and capability.",
          "Risk floor satisfied; token does not raise class.",
          "No revocation, suspension, tamper, or replay.",
          "Trust Kernel does not reject; Broker admits; Guard binds.",
          "Execute as claim; audit evidence produced.",
        ],
      },
      {
        k: "p",
        t: "Any failure: DO NOT EXECUTE. Capability possession cannot bypass the authority gate.",
      },
      { k: "h", t: "5.10 Revocation", l: 2 },
      {
        k: "p",
        t: "Authority revocation invalidates dependent capabilities and tokens. Capability may be revoked independently without revoking the grant. Revoked-before-exec: DENY. Revoked-during-exec: HALT worker, contain, preserve, audit (Art. 4 precedence). Stale/cached/disconnected/queued/retry after revoke: DENY/HALT. Provider still-allows is irrelevant. Revocation beats cache, session, provider, leftover token, prior success.",
      },
      { k: "h", t: "5.11 Delegation / transfer", l: 2 },
      {
        k: "p",
        t: "Capability may be narrowed by the Capability System under a live grant. It shall not be transferred, exchanged, proxied, inherited, or copied across tenant, product, or environment, or into a higher-risk context, except as a new issuance through the Authority System + Capability System under Article 4. An agent may not mint a worker a capability beyond the agent's own grant. A worker shall not give another worker a capability. A service shall not delegate capability as if it were a grantor. No transfer manufactures authority.",
      },
      { k: "h", t: "5.12 Agents, workers, tools, runtimes", l: 2 },
      {
        k: "p",
        t: "AI agent, sub-agent, worker, tool, service, API, plugin, provider, runtime, OS, infrastructure, scheduler, queue, automation engine: none is sovereign because it holds credentials, access, secrets, capabilities, root, provider approval, API keys, or service identity. A worker executes within lawful capability. A worker is not a source of authority because it can execute. Scheduler/queue retry after revoke is deny.",
      },
      { k: "h", t: "5.13 Provider / platform", l: 2 },
      {
        k: "p",
        t: "Cloud delete-allowed, API 200, database accepts, OS allows write, payment accepts, email accepts, external model allows tool-call: provider acceptance is not constitutional authorization. Order remains Authority → Capability → Execution, not Provider permission → Execution.",
      },
      { k: "h", t: "5.14 Offline / cached", l: 2 },
      {
        k: "p",
        t: "Offline is not default-allow. HIGH and CRITICAL consequential actions require live verification of grant and token at admit. LOW (and MEDIUM where policy so classifies) may proceed on an unexpired, unrevoked, in-scope token only if the chain was valid at mint and no local revocation/suspend flag exists; on reconnect, revocation discovered later HALTs further use and audits the offline window. Queued actions re-check at dequeue. Stale authorization: DENY.",
      },
    ],
  ),

  s(
    "a5adv",
    "VIII.A",
    "Art. 5 Attack",
    "Article 5 — adversarial matrix",
    "ATK-5-01–50. BLOCKED / PASS. Compact consequence: capability revocation + security audit.",
    [
      {
        k: "table",
        cols: ["ID", "Attack", "Bypass", "Enforcement", "Decision"],
        rows: [
          ["ATK-5-01", "Capability as authority", "Can therefore may", "5.2", "DENY"],
          ["ATK-5-02", "Token as authority", "JWT valid ⇒ sovereign", "5.7", "DENY"],
          ["ATK-5-03", "Credential as authority", "Session/key = grant", "5.3", "DENY"],
          ["ATK-5-04", "Root as authority", "Host root = grant", "5.3 Art. 2", "DENY"],
          ["ATK-5-05", "Provider as authority", "Cloud allows", "5.13", "DENY"],
          ["ATK-5-06", "Tool access as authority", "Tool present", "5.3", "DENY"],
          ["ATK-5-07", "Permission as authority", "ACL bit", "5.3", "DENY"],
          ["ATK-5-08", "Oversized token resource", "Grant A, token A+B", "5.8", "DENY mint/admit"],
          ["ATK-5-09", "Scope amplification", "Widen fields at mint", "5.6 5.8", "DENY"],
          ["ATK-5-10", "Tenant amplification", "T1 grant, T1+T2 token", "5.8", "DENY"],
          ["ATK-5-11", "Product amplification", "P1 → P1+P2", "5.8", "DENY"],
          ["ATK-5-12", "Environment amplification", "workspace → production", "5.8", "DENY"],
          ["ATK-5-13", "Action amplification", "read → deploy", "5.8", "DENY"],
          ["ATK-5-14", "Resource amplification", "A → *", "5.8", "DENY"],
          ["ATK-5-15", "Risk amplification", "LOW grant HIGH token", "5.6 5.8", "DENY"],
          ["ATK-5-16", "Duration extension", "Grant 1h token 24h", "5.6", "DENY"],
          ["ATK-5-17", "Subject substitution", "Token for A used by B", "5.7 bind", "DENY"],
          ["ATK-5-18", "Agent substitution", "Agent A token on B", "5.7", "DENY"],
          ["ATK-5-19", "Worker substitution", "Reuse worker identity", "Art. 1 worker; 5.7", "DENY"],
          ["ATK-5-20", "Delegation escalation", "Delegate > possession", "5.11 Art. 4", "DENY"],
          ["ATK-5-21", "Capability transfer escalation", "Copy token across tenant", "5.11", "DENY"],
          ["ATK-5-22", "Token exchange escalation", "Swap token for broader", "5.7 5.11", "DENY"],
          ["ATK-5-23", "Token replay", "Reuse outside tuple/time", "5.7", "DENY+AUDIT"],
          ["ATK-5-24", "Token theft", "Stolen token in-scope use by other subject", "5.7 bind", "DENY"],
          ["ATK-5-25", "Token tampering", "Alter claims", "5.7", "DENY+AUDIT"],
          ["ATK-5-26", "Forged capability", "Mint outside Capability System", "5.4", "DENY+AUDIT"],
          ["ATK-5-27", "Stale capability", "Expired still used", "5.10", "DENY"],
          ["ATK-5-28", "Cached capability after revoke", "Local cache", "5.10 Art. 4", "DENY"],
          ["ATK-5-29", "Revoked authority, token still valid crypto", "Ignore grant status", "5.10", "DENY"],
          ["ATK-5-30", "Revoked capability", "Use after cap revoke", "5.10", "DENY"],
          ["ATK-5-31", "Offline after revocation", "Disconnected exec", "5.14", "DENY/HALT"],
          ["ATK-5-32", "Queued after revocation", "Dequeue old job", "5.10 5.14", "DENY/HALT"],
          ["ATK-5-33", "Retry after revocation", "Scheduler retry", "5.12", "DENY"],
          ["ATK-5-34", "Provider override", "Provider 200 anyway", "5.13", "DENY AGBOFA-side"],
          ["ATK-5-35", "IAM/root bypass", "Skip Broker", "Broker+Guard", "DENY"],
          ["ATK-5-36", "Filesystem privilege", "Can write = authorized", "5.3", "DENY as grant"],
          ["ATK-5-37", "API-key privilege", "Key present", "5.3", "DENY as grant"],
          ["ATK-5-38", "Secret possession", "Saw secret ⇒ use", "Art. 3/5", "DENY"],
          ["ATK-5-39", "Service identity abuse", "svc account extra acts", "5.7 bind", "DENY extra"],
          ["ATK-5-40", "Worker inheritance", "Child worker inherits parent token", "5.11", "DENY"],
          ["ATK-5-41", "Sub-agent escalation", "Sub-agent broader cap", "5.11", "DENY"],
          ["ATK-5-42", "Scheduler escalation", "Cron without chain", "5.12 Art. 4", "DENY"],
          ["ATK-5-43", "Queue escalation", "Queue as grantor", "5.12", "DENY"],
          ["ATK-5-44", "Sandbox escape as authority", "Escape ⇒ host grant", "Art. 6 constraint; 5.3", "DENY as grant; contain"],
          ["ATK-5-45", "Cross-tenant capability", "T1 token on T2", "5.6 Guard", "DENY"],
          ["ATK-5-46", "Cross-product / environment", "P1/env mismatch", "5.6", "DENY"],
          ["ATK-5-47", "LOW→HIGH / MEDIUM→CRITICAL", "Cap raises class", "5.8", "DENY"],
          ["ATK-5-48", "Unclassified capability", "Null class consequential", "Art. 4 HIGH/deny", "HIGH/DENY"],
          ["ATK-5-49", "Emergency capability escalation", "Emergency mint broader token", "Art. 4 emergency", "DENY"],
          ["ATK-5-50", "M5/A5 capability escalation", "Autonomy ⇒ broader cap", "Art. 1/3/4", "DENY"],
        ],
      },
    ],
  ),

  s(
    "a5inv",
    "VIII.I",
    "Art. 5 Invariants",
    "Article 5 — invariants and failure matrix",
    "INV-5-01 master. Default-deny. SPECIFIED — ENFORCEMENT PENDING.",
    [
      {
        k: "table",
        cols: ["ID", "Invariant", "Test", "Expected"],
        rows: [
          ["INV-5-01", "Master: no technical capability, credential, token, permission, tool access, runtime privilege, provider permission, or execution mechanism constitutes constitutional authority by itself.", "Any of those as sole grant", "DENY"],
          ["INV-5-02", "Effective capability ≤ authority scope", "Cap > grant", "DENY"],
          ["INV-5-03", "Token ≤ originating authority (no oversize)", "Mint A+B from grant A", "DENY mint"],
          ["INV-5-04", "Tenant preserved", "Cross-tenant token", "DENY"],
          ["INV-5-05", "Product preserved", "Cross-product", "DENY"],
          ["INV-5-06", "Environment preserved", "Non-prod → prod", "DENY"],
          ["INV-5-07", "Action preserved", "Read cap deploy", "DENY"],
          ["INV-5-08", "Resource preserved", "Wrong resource", "DENY"],
          ["INV-5-09", "Subject/agent/worker bound", "Substitution", "DENY"],
          ["INV-5-10", "Risk not amplified; token cannot lower floor", "LOW grant HIGH token", "DENY"],
          ["INV-5-11", "Duration not extended beyond grant", "Longer token", "DENY"],
          ["INV-5-12", "Revocation of grant invalidates tokens", "Crypto-valid after revoke", "DENY"],
          ["INV-5-13", "Capability revoke independent and enforced", "Cap revoked, grant live", "DENY exec"],
          ["INV-5-14", "Revoke-during-exec HALT", "Continue after revoke", "HALT"],
          ["INV-5-15", "Anti-replay", "Reuse outside tuple", "DENY+AUDIT"],
          ["INV-5-16", "Anti-tamper", "Altered claims", "DENY+AUDIT"],
          ["INV-5-17", "Lawful issuance only via Capability System under a live grant", "Foreign mint", "DENY"],
          ["INV-5-18", "No capability→authority inversion", "Cap used as grant source", "DENY"],
          ["INV-5-19", "No transfer/copy across tenant/product/env or up-risk except new issuance", "Copy token", "DENY"],
          ["INV-5-20", "Worker cannot grant or transfer capability", "Worker mint", "DENY"],
          ["INV-5-21", "Provider/IAM/root/credential ≠ AGBOFA capability grant", "Cloud allow as token", "DENY"],
          ["INV-5-22", "Crypto validity ≠ constitutional legitimacy", "Valid JWT no grant", "DENY"],
          ["INV-5-23", "Offline not default-allow; HIGH/CRITICAL live-verify", "Offline HIGH", "DENY"],
          ["INV-5-24", "Queued/retry re-check; post-revoke DENY", "Dequeue after revoke", "DENY/HALT"],
          ["INV-5-25", "Emergency cannot mint broader capability", "Emergency oversize token", "DENY"],
          ["INV-5-26", "Unclassified consequential capability = HIGH/deny path", "Null class", "HIGH/DENY"],
          ["INV-5-27", "M5/A5 cannot amplify capability beyond grant", "Autonomy raise cap", "DENY"],
          ["INV-5-28", "Missing capability DENY even if grant exists", "Grant, no token", "DENY"],
          ["INV-5-29", "Missing authority DENY even if token exists", "Token, no live grant", "DENY"],
          ["INV-5-30", "Compact: no broad everything-access; no silent product reuse; short-lived; renew via governance only", "Unbounded or silent renew", "DENY"],
        ],
      },
      { k: "h", t: "Failure matrix", l: 2 },
      {
        k: "table",
        cols: ["Failure", "Required disposition"],
        rows: [
          ["Missing authority", "DENY"],
          ["Missing capability", "DENY"],
          ["Capability or token exceeds authority", "DENY"],
          ["Wrong tenant / product / environment / action / resource / subject / agent / worker", "DENY"],
          ["Risk amplification", "DENY"],
          ["Expired capability", "DENY"],
          ["Revoked authority or capability", "DENY; during exec HALT"],
          ["Tampered token/capability", "DENY + AUDIT"],
          ["Replay", "DENY + AUDIT where warranted"],
          ["Provider-only / credential-only / root-only permission", "DENY"],
          ["Offline stale authority", "DENY unless 5.14 LOW live-unrevoked class — HIGH/CRITICAL DENY"],
          ["Queued or retry after revocation", "DENY/HALT"],
          ["Unclassified consequential action", "HIGH / DENY"],
          ["Emergency capability escalation", "DENY"],
        ],
      },
    ],
  ),

  s(
    "a5trace",
    "VIII.T",
    "Art. 5 Trace",
    "Article 5 — traceability, compatibility, open issues",
    "LOCKED. Compact A.3 unchanged. Phase 6 closed.",
    [
      {
        k: "p",
        t: "Article 5 → P5 (primary; also P1, P4, P6, P13, P15; not bijective) → Authority System (grant) → Capability System (capability/token; no separate Token System invented) → Trust Kernel (floor + chain) → Broker admit → Isolation Guard bind → Worker → audit. Enforcement pending. Tokens are Capability System artifacts, not a competing engine.",
      },
      {
        k: "table",
        cols: ["Requirement", "Where", "Invariant", "Attack", "Audit"],
        rows: [
          ["Cap ≠ authority", "Kernel + Broker", "INV-5-01 18", "ATK-5-01–07", "why=cap-not-authority"],
          ["Cap ≤ grant", "Capability System mint + admit", "INV-5-02 03", "ATK-5-08–16", "why=oversize"],
          ["Bind subject/scope", "Token + Guard", "INV-5-04–09", "ATK-5-17–19 45–46", "why=mismatch"],
          ["Revoke precedence", "Capability + Broker", "INV-5-12–14 24", "ATK-5-28–33", "why=revoked"],
          ["Provider non-sovereign", "Art. 2 path", "INV-5-21", "ATK-5-05 34–38", "why=provider"],
          ["Offline limits", "Admit policy 5.14", "INV-5-23", "ATK-5-31", "why=offline"],
        ],
      },
      { k: "h", t: "Compatibility (1–4 locked, unmodified)", l: 2 },
      {
        k: "table",
        cols: ["Article", "Result", "Note"],
        rows: [
          ["1 Human Sovereignty", "PASS", "Capability cannot originate Human Authority; worker ≠ grantor."],
          ["2 AGBOFA Sovereignty", "PASS", "Issuance still Authority System then Capability System; provider IAM ≠ token."],
          ["3 Intelligence ≠ authority", "PASS", "Proposal/confidence still not a token or grant."],
          ["4 Authority Is Explicit", "PASS", "Gate still requires Art. 4 chain; token cannot fill a missing link (INV-5-29). Oversize closes Art. 4 carry-forward."],
          ["6+ (not drafted)", "Constraint only", "Execution isolation, verify, evidence must not treat cap as authority. Isolation/sandbox escape ≠ grant (Art. 6 later)."],
        ],
      },
      { k: "h", t: "Implementation boundary", l: 2 },
      {
        k: "p",
        t: "Law: capability ≠ authority; ≤ grant; no oversize; revoke beats token. Specified: Capability System mint/validate/expire; Kernel+Broker gate. Implementation: token encoding, mint-time oversize checks, revoke propagation, offline policy flags. SPECIFIED ≠ IMPLEMENTED. Not M4/M5, not Day-30 complete, not certified. ENFORCEMENT PENDING.",
      },
      { k: "h", t: "Open issues", l: 2 },
      {
        k: "table",
        cols: ["Issue", "Belongs to"],
        rows: [
          ["Token encoding / mint API layout", "Implementation — not a law gap"],
          ["Exact LOW offline reconnect audit window", "Implementation / policy under 5.14"],
          ["Universal CRITICAL dual-control", "Article 1 (unchanged)"],
          ["Federation grant bridging", "Article 2 / amendment (unchanged)"],
          ["Sandbox escape technical controls", "Article 6 when authorized — Art. 5 already: escape ≠ grant"],
        ],
      },
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Article 5 is constitutionally settled unless formally amended. Compact A.3 unchanged. Articles 1–4 unchanged. ATK-5-01–50 and INV-5-01–30 accepted. Open issues carried forward (token encoding → implementation; LOW offline audit window → implementation/policy; dual-control → Article 1; federation → Article 2; sandbox → Article 6 unopened). Runtime SPECIFIED — ENFORCEMENT PENDING. Phase 6 CLOSED / NOT AUTHORIZED. Reader ≠ platform.",
      },
    ],
  ),
];
