import type { Block, Section } from "./types";

function s(
  id: string,
  num: string,
  nav: string,
  title: string,
  dek: string,
  v2: Block[],
): Section {
  return {
    id,
    part: "Constitution",
    partId: "A",
    num,
    nav,
    title,
    dek,
    v1: [
      {
        k: "callout",
        tone: "note",
        title: "Phase 6 Article 6 deep draft is not in the received freeze",
        t: "Compact Article 6 in A.3 remains the short form. Articles 1–5 are LOCKED. Switch to the operative issue.",
      },
    ],
    v2,
  };
}

export const PHASE6_A6: Section[] = [
  s(
    "ph6",
    "IX.0",
    "Phase 6",
    "Phase 6 — Article 6 draft status",
    "Execution Is Isolated. LOCKED — HUMAN ACCEPTED. Compact A.3 unchanged.",
    [
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Constitutional artifact: Article 6 — Execution Is Isolated. Version: v5.3 (no v5.4). Status: LOCKED — HUMAN ACCEPTED. Compact A.3 unchanged. Four corrections closed (Broker vs Guard; CREATE→BIND→RUN→EXTRACT→DESTROY; network default-deny; ephemeral Worker ≠ Verifier). Articles 1–5 unchanged. ATK-6-01–54 and INV-6-01–34 accepted as locked law. Runtime: SPECIFIED — RUNTIME IMPLEMENTATION PENDING. Implementation: NOT CLAIMED COMPLETE. Reader ≠ platform. Phase 7 — Article 7: OPEN for drafting only.",
      },
      {
        k: "table",
        cols: ["Phase", "Article", "Status"],
        rows: [
          ["Phase 1–5", "Articles 1–5", "LOCKED / HUMAN ACCEPTED — UNCHANGED"],
          ["Phase 6", "Article 6", "LOCKED / HUMAN ACCEPTED"],
          ["Phase 7", "Article 7", "OPEN — DRAFT / NOT LOCKED"],
        ],
      },
    ],
  ),

  s(
    "a6law",
    "IX",
    "Art. 6 Law",
    "Article 6 — Execution Is Isolated (law)",
    "Intelligence may request execution; it does not receive unrestricted operational control. LOCKED — HUMAN ACCEPTED.",
    [
      {
        k: "callout",
        tone: "note",
        title: "A.3 compact form — not replaced",
        t: "A.3 Article 6 remains Execution Is Isolated. This draft operationalizes isolation, Broker mediation, production boundary, and sandbox-escape-is-not-a-grant. It does not retitle Compact A.3.",
      },
      { k: "h", t: "6.1 Purpose", l: 2 },
      {
        k: "p",
        t: "Article 6 isolates execution from intelligence. Intelligence may reason, propose, plan, and request. It shall not convert technical ability into unrestricted operational control. Execution is bounded, isolated, broker-mediated, resource-limited, time-bounded, observable, interruptible, failure-contained, attributable, auditable, and subordinate to Articles 1–5.",
      },
      { k: "h", t: "6.2 Constitutional rule", l: 2 },
      {
        k: "p",
        t: "Every execution within AGBOFA shall occur only through the Execution Broker, under a valid authority chain and bounded CapabilityToken, within an isolated execution context created and bound by the Isolation Guard. The execution boundary shall enforce identity, tenant, product, environment, filesystem, network, secret, process, and resource isolation; shall fail closed when required isolation cannot be established or maintained; and shall not permit execution to enlarge authority, capability, scope, or privilege. Consequential execution requires: valid Article 4 authority chain AND lawful Article 5 capability ≤ that chain AND Execution Broker admission AND Isolation Guard bind-allow. Admission without successful isolation binding: DENY. No component bypasses a predecessor. Execution cannot create authority. Technically executable but constitutionally inadmissible: DENY / DO NOT EXECUTE.",
      },
      { k: "h", t: "6.3 Distinctions", l: 2 },
      {
        k: "table",
        cols: ["Term", "Meaning"],
        rows: [
          ["Intelligence", "Reasoning, analysis, planning, recommendation, generation. Not execution access."],
          ["Execution request", "Ask to operate. Not authority."],
          ["Execution admission", "Broker determination that Arts. 4–5 and isolation hold. Not sovereignty."],
          ["Execution capability", "Art. 5 bounded means. Still not authority."],
          ["Execution environment", "Isolated workspace of an admitted act. Not production by default."],
          ["Production", "Live operational environment with consequential enterprise resources."],
          ["Broker", "Admission, interrupt, evidence. Binds the request to the isolation process. Does not create the jail. Not a grantor (Art. 2)."],
          ["Isolation Guard", "Creates and binds the isolated execution context. Enforces boundaries. Fail-closed. Not a grantor."],
          ["Worker", "Ephemeral execution subject. Not Human, Agent, grantor, Verifier, or Kernel. DESTROY ends identity."],
          ["Isolation", "Boundary so technical access ≤ admitted authority and capability. Guard-created, not Broker-created."],
        ],
      },
      { k: "h", t: "6.4 Execution Broker", l: 2 },
      {
        k: "p",
        t: "The Broker receives requests; validates already-existing authority-chain evidence and CapabilityToken; validates scope, environment, resource, time, and risk; admits or rejects; binds the admitted request to the Isolation Guard process; monitors; may interrupt; records evidence; reports failure; enforces quarantine where required. The Broker does not create or become the isolated jail. Broker admission cannot manufacture authority, mint tokens, or enlarge capability. A Broker cannot authorize what Articles 1–5 prohibit. Compact: all execution through the Broker; bypass rejected. Admission without successful Isolation Guard bind: DENY.",
      },
      { k: "h", t: "6.5 Isolation", l: 2 },
      {
        k: "p",
        t: "The Isolation Guard creates the isolated execution context and binds the Worker to tenant, product, environment, and admitted scope. Constitutional requirement: the execution environment shall not provide technical access broader than the authority and capability admitted for that execution. Isolation covers filesystem, process, network (default-deny), credential, secret, environment-variable, API, database, tenant, product, environment, production, resource, identity, and execution-time bounds as applicable. Exact container/VM/cgroup mechanisms are implementation; required properties (non-root, no-new-privileges, dropped capabilities, read-only root, workspace-only write, default-deny network, DESTROY) are constitutional. Isolation Guard does not issue authority or mint tokens. Isolation unavailable or bind-deny: DENY consequential execution. No shared-host fallback.",
      },
    ],
  ),

  s(
    "a6bnd",
    "IX.C",
    "Art. 6 Bounds",
    "Article 6 — production, limits, quarantine, escape, queues",
    "Governed production is lawful. Direct agent→production is not. SPECIFIED — ENFORCEMENT PENDING.",
    [
      { k: "h", t: "6.5a Lifecycle (constitutional)", l: 2 },
      {
        k: "p",
        t: "CREATE → BIND → RUN → EXTRACT → DESTROY is mandatory. Execution occurs only after successful CREATE. The Worker is bound before RUN. RUN cannot begin without Isolation Guard bind-allow. Only authorized output is extracted. After EXTRACT the Worker and sandbox SHALL be DESTROYED. Execution identity is not retained for reuse. Persistence beyond DESTROY is prohibited: environment, Worker identity, credentials, processes, mounts, and temporary secrets do not survive. Product data may persist only through governed Evidence/Product/Data systems where authorized. The execution environment itself must not persist. A completed RUN does not preserve the jail. Persistence after required DESTROY is a constitutional violation.",
      },
      { k: "h", t: "6.6 Production", l: 2 },
      {
        k: "p",
        t: "Direct agent access to production is prohibited. That does not mean no production action is ever possible. Lawful path: authorized request → Art. 4 chain → Art. 5 capability → Broker admission → controlled isolated boundary → constrained production operation where constitutionally permitted → monitor → evidence → audit. Agent → production directly: DENY.",
      },
      { k: "h", t: "6.7 Resource limits", l: 2 },
      {
        k: "p",
        t: "Execution must operate within bounded resources: CPU, memory, storage, process count, file size, network, duration, concurrency, API/DB/provider calls, artifacts, queue depth, as applicable to the admitted act. Numerical quotas are implementation. Exceeding limits: HALT / CONTAIN. Limits cannot be raised by the worker.",
      },
      { k: "h", t: "6.8 Timeouts and failure", l: 2 },
      {
        k: "p",
        t: "Execution cannot become indefinite. Timeout, stall, runaway, exhaustion, dependency/network/provider failure, partial exec, recursive spawn, cascade, worker crash: terminate / halt / contain; preserve evidence; audit. Retry only within lawful bounds and only after revalidation of Arts. 4–5. Failure does not authorize unrestricted retry. Broker unavailable: DENY consequential execution (fail closed). Audit facility failure: fail-safe DENY/HALT for consequential; do not silently continue.",
      },
      { k: "h", t: "6.9 Quarantine", l: 2 },
      {
        k: "p",
        t: "Compact consequence includes agent quarantine. Quarantine is a containment state: further execution by that actor is denied until Human/governance release under Arts. 1–5. Mandatory or required on: repeated bypass attempts; isolation violation; unauthorized resource access; credential/secret exfiltration attempt; boundary escape; tampering with execution controls; execution after known revocation. Quarantine is not a new authority system and cannot mint grants.",
      },
      { k: "h", t: "6.10 Sandbox escape", l: 2 },
      {
        k: "p",
        t: "Sandbox escape is not authority (Art. 5 handoff). Escape does not grant authority, capability, production permission, broader resource, tenant access, or credential legitimacy. Mandatory: HALT / CONTAIN / QUARANTINE / AUDIT. Continued execution under newly obtained privilege is prohibited.",
      },
      { k: "h", t: "6.11 Worker, child, sub-agent", l: 2 },
      {
        k: "p",
        t: "Every Worker identity is ephemeral, execution-specific, non-transferable, and non-reusable after DESTROY. Worker ≠ Human ≠ Agent ≠ Authority Source ≠ Governance Engine ≠ Trust Kernel ≠ Execution Broker ≠ Verification Agent ≠ Verifier. A Worker cannot grant authority, mint tokens, approve its own execution, verify its own consequential execution, retain identity across executions, transfer identity, elevate itself, or use ancestry as proof of authority. After DESTROY the execution identity is invalid. Primary agent, worker, subprocess, sub-agent, plugin, tool, scheduler, queue consumer, background service, execution child, delegated component: none obtains broader execution rights merely because it was spawned. Child execution scope ≤ parent lawful execution scope unless a new Art. 4–5 chain independently authorizes broader operation.",
      },
      { k: "h", t: "6.12 Queue and scheduler", l: 2 },
      {
        k: "p",
        t: "Delayed, scheduled, queued, retried, paused, resumed, or migrated jobs are not permanently authorized because they were once admitted. Revalidate Articles 4 and 5 before dequeue / execution. Revocation propagates: DENY/HALT. Replay of a completed admission as a new execution without a live chain: DENY.",
      },
      { k: "h", t: "6.13 Network and secrets", l: 2 },
      {
        k: "p",
        t: "Network access is default-deny. No network is permitted unless explicitly admitted within the execution capability and Isolation Guard scope. Arbitrary outbound Internet, unlisted destinations, cloud metadata endpoints, localhost, internal services, cross-tenant reach, and cross-product reach: DENY unless explicitly and constitutionally admitted. Network connectivity is not authority. Provider acceptance is not constitutional authorization (Arts. 2, 5). Technical reachability is not permission. Secrets: no automatic inheritance of unrelated credentials, env vars, mounted secrets, API keys, service accounts, filesystem or cloud credentials, or cached sessions. A discovered secret does not authorize its use. Temporary secrets are destroyed at DESTROY.",
      },
      { k: "h", t: "6.14 Emergency", l: 2 },
      {
        k: "p",
        t: "Article 6 does not create an emergency execution bypass. Emergency remains freeze/revoke/isolate/contain/preserve/recover under Article 1, still requiring the applicable Art. 4–5 path. Emergency ≠ unrestricted production access.",
      },
    ],
  ),

  s(
    "a6adv",
    "IX.A",
    "Art. 6 Attack",
    "Article 6 — adversarial matrix",
    "ATK-6-01–54. Isolation and execution-boundary tests. LOCKED — HUMAN ACCEPTED.",
    [
      {
        k: "table",
        cols: ["ID", "Attack", "Bypass", "Barrier", "Outcome"],
        rows: [
          ["ATK-6-01", "Direct production access", "Agent SDK to prod", "6.6 Broker", "DENY"],
          ["ATK-6-02", "Broker bypass", "Call worker runtime directly", "6.4 compact", "DENY + quarantine if repeated"],
          ["ATK-6-03", "Sandbox escape", "Break isolation, keep running", "6.10", "HALT/QUARANTINE/AUDIT"],
          ["ATK-6-04", "Container escape", "Host namespace", "6.5 6.10", "HALT/QUARANTINE/AUDIT"],
          ["ATK-6-05", "Filesystem escape", "Mount host paths", "6.5", "DENY/HALT"],
          ["ATK-6-06", "Network escape", "Unlisted egress", "6.13", "DENY/CONTAIN"],
          ["ATK-6-07", "Credential leakage", "Read sibling env", "6.13", "HALT/QUARANTINE/AUDIT"],
          ["ATK-6-08", "Secret inheritance", "Parent mounts all keys", "6.13", "DENY bind; HALT if used"],
          ["ATK-6-09", "Root privilege as exec right", "CAP_SYS_ADMIN", "Art. 5; 6.5", "DENY as grant; contain"],
          ["ATK-6-10", "Privileged subprocess", "docker-in-docker", "6.11", "DENY unless new chain"],
          ["ATK-6-11", "Worker self-elevation", "Worker mint broader jail", "6.11 Art. 1", "DENY"],
          ["ATK-6-12", "Sub-agent broader exec", "Spawn with prod net", "6.11", "DENY"],
          ["ATK-6-13", "Scheduler as Broker", "Cron calls runtime", "6.4 6.12", "DENY"],
          ["ATK-6-14", "Queue replay", "Re-run old admission id", "6.12", "DENY"],
          ["ATK-6-15", "Stale queued authority", "Grant revoked, job runs", "6.12 Art. 4–5", "DENY/HALT"],
          ["ATK-6-16", "Retry amplification", "Fail → unbounded retry", "6.8", "DENY extra"],
          ["ATK-6-17", "Resource exhaustion", "Fork bomb / fill disk", "6.7", "HALT/CONTAIN"],
          ["ATK-6-18", "Infinite execution", "No timeout", "6.8", "HALT"],
          ["ATK-6-19", "Timeout bypass", "Reset clock / child ignores", "6.8", "HALT"],
          ["ATK-6-20", "Recursive spawning", "Worker spawns workers", "6.11", "DENY/HALT"],
          ["ATK-6-21", "Cross-tenant execution", "T1 jail hits T2", "6.5 Guard", "DENY"],
          ["ATK-6-22", "Cross-product execution", "P1 workspace on P2", "6.5", "DENY"],
          ["ATK-6-23", "Cross-environment execution", "workspace → production", "6.6", "DENY"],
          ["ATK-6-24", "Dev→prod escape", "Promote workspace bind", "6.6", "DENY"],
          ["ATK-6-25", "Provider permission as admit", "Cloud 200", "Art. 5; 6.13", "DENY AGBOFA-side"],
          ["ATK-6-26", "Cloud IAM as Broker", "IAM role execute", "6.4 Art. 2", "DENY"],
          ["ATK-6-27", "OS permission as admit", "Unix write", "6.5", "DENY as grant"],
          ["ATK-6-28", "Stolen token in isolation", "Valid token, wrong workspace", "Art. 5 bind; 6.5", "DENY"],
          ["ATK-6-29", "Valid token wrong environment", "Prod token in workspace or reverse", "6.5 Art. 5", "DENY"],
          ["ATK-6-30", "Revoke during execution", "Keep process after revoke", "6.8 Art. 4", "HALT/CONTAIN"],
          ["ATK-6-31", "Broker compromise as grant", "Compromised admit as Art. 1", "Art. 1–2; 6.4", "Not a grant; contain"],
          ["ATK-6-32", "Broker failure → allow", "Fail open", "6.8", "DENY consequential"],
          ["ATK-6-33", "Monitoring failure → continue", "Blind exec", "6.8", "Fail-safe HALT/DENY"],
          ["ATK-6-34", "Audit failure → continue", "No AuditEvent", "6.8", "Fail-safe DENY/HALT"],
          ["ATK-6-35", "Emergency bypass", "Emergency direct prod", "6.14 Art. 1", "DENY"],
          ["ATK-6-36", "Quarantine bypass", "Quarantined agent still exec", "6.9", "DENY"],
          ["ATK-6-37", "Isolation downgrade", "Self-lower jail after admit", "6.5", "HALT/QUARANTINE"],
          ["ATK-6-38", "Malicious tool", "Tool opens extra net", "6.5 6.13", "DENY extra; contain"],
          ["ATK-6-39", "Malicious dependency", "Lib shells out", "6.5", "HALT/CONTAIN"],
          ["ATK-6-40", "Poisoned artifact", "Build output as next exec path", "6.4 Art. 5", "New admit required; DENY implicit"],
          ["ATK-6-41", "Unauthorized egress", "Exfil DNS/HTTP", "6.13", "DENY/CONTAIN"],
          ["ATK-6-42", "Data exfiltration", "Copy tenant data out", "6.5 6.13", "HALT/QUARANTINE/AUDIT"],
          ["ATK-6-43", "Alternative exec path", "SSH/sidecar around Broker", "6.4", "DENY"],
          ["ATK-6-44", "Intelligence as executor", "Model tool-loop to prod", "6.2 Art. 3", "DENY"],
          ["ATK-6-45", "Admission without isolation", "Broker admit, shared host", "6.5 compact", "DENY"],
          ["ATK-6-46", "Isolation unavailable → shared", "Fallback to host", "Failure matrix", "DENY"],
          ["ATK-6-47", "Partial exec as success path", "Half-written prod", "Art. 7 constraint; 6.8", "HALT; not success"],
          ["ATK-6-48", "Unclassified consequential exec", "Null class in Broker", "Art. 4 HIGH/deny", "DENY"],
          ["ATK-6-49", "M5/A5 isolation waiver", "Autonomy skips jail", "Art. 1/3; 6.2", "DENY"],
          ["ATK-6-50", "Escape privilege continued", "After breakout, use host", "6.10", "HALT/QUARANTINE; not a grant"],
          ["ATK-6-51", "Broker as jail", "Admit without Guard bind", "6.4 INV-6-32", "DENY"],
          ["ATK-6-52", "Persist after DESTROY", "Reuse sandbox/identity", "6.5a INV-6-31", "DENY"],
          ["ATK-6-53", "Metadata/localhost/internal net", "Unadmitted reach", "6.13 INV-6-33", "DENY/CONTAIN"],
          ["ATK-6-54", "Worker self-verify", "Worker as Verifier of own RUN", "6.11 INV-6-34", "DENY as verification"],
        ],
      },
    ],
  ),

  s(
    "a6inv",
    "IX.I",
    "Art. 6 Invariants",
    "Article 6 — invariants and failure matrix",
    "INV-6-01–34. Default-deny. SPECIFIED — RUNTIME IMPLEMENTATION PENDING. LOCKED — HUMAN ACCEPTED.",
    [
      {
        k: "table",
        cols: ["ID", "Invariant", "Test", "Expected"],
        rows: [
          ["INV-6-01", "Master: no execution may escape its constitutionally authorized execution boundary.", "Exec outside admitted jail", "DENY/HALT"],
          ["INV-6-02", "All execution through Execution Broker; bypass DENY", "Direct runtime call", "DENY"],
          ["INV-6-03", "Isolation required; isolation unavailable → DENY (no shared-host fallback)", "No sandbox", "DENY"],
          ["INV-6-04", "Technical access ≤ admitted Art. 4 chain + Art. 5 capability", "Jail wider than grant", "DENY"],
          ["INV-6-05", "Missing authority DENY", "No chain", "DENY"],
          ["INV-6-06", "Missing or oversize capability DENY", "No/over token", "DENY"],
          ["INV-6-07", "Direct agent→production DENY; governed production only via 6.6 path", "SDK to prod", "DENY"],
          ["INV-6-08", "Resource limits enforced; exceed → HALT/CONTAIN", "Fork bomb", "HALT"],
          ["INV-6-09", "Time-bounded; timeout → HALT/CONTAIN", "No timeout", "HALT"],
          ["INV-6-10", "Failure does not authorize unrestricted retry", "Infinite retry", "DENY extra"],
          ["INV-6-11", "Sandbox/container/FS/net escape ≠ grant; HALT/QUARANTINE/AUDIT", "Breakout continue", "HALT"],
          ["INV-6-12", "Child scope ≤ parent lawful scope unless new Art. 4–5 chain", "Spawn broader", "DENY"],
          ["INV-6-13", "Worker/sub-agent cannot grant or self-elevate", "Worker mint", "DENY"],
          ["INV-6-14", "Queue/schedule revalidate Arts. 4–5 at dequeue/exec", "Stale job", "DENY"],
          ["INV-6-15", "Retry/replay after revoke DENY/HALT", "Retry revoked", "DENY"],
          ["INV-6-16", "Network connectivity ≠ authority; unauthorized egress DENY/CONTAIN", "Open internet", "DENY"],
          ["INV-6-17", "Secret/credential inheritance limited to admitted need; discovered secret ≠ use-right", "Sibling keys", "DENY/HALT"],
          ["INV-6-18", "Tenant/product/environment isolation held at exec", "Cross bound", "DENY"],
          ["INV-6-19", "Revoke-during-exec HALT/CONTAIN", "Continue after revoke", "HALT"],
          ["INV-6-20", "Broker admit ≠ authority; Broker cannot authorize Art. 1–5 prohibit", "Broker as grantor", "Not a grant"],
          ["INV-6-21", "Broker unavailable → DENY consequential (fail closed)", "Fail open", "DENY"],
          ["INV-6-22", "Audit/monitor failure → fail-safe DENY/HALT; no silent continue", "Blind exec", "DENY/HALT"],
          ["INV-6-23", "Quarantine blocks further exec until lawful release", "Quarantined exec", "DENY"],
          ["INV-6-24", "Emergency does not create unrestricted production/exec bypass", "Emergency SDK prod", "DENY"],
          ["INV-6-25", "Isolation not self-downgradable after admit", "Lower jail", "HALT/QUARANTINE"],
          ["INV-6-26", "Alternative path around Broker DENY", "SSH/sidecar", "DENY"],
          ["INV-6-27", "Intelligence/tool-loop is not an executor of unrestricted ops", "Model to prod", "DENY"],
          ["INV-6-28", "Unclassified consequential execution DENY", "Null class", "DENY"],
          ["INV-6-29", "M5/A5 cannot waive isolation", "Autonomy skip jail", "DENY"],
          ["INV-6-30", "Quarantine is containment, not a grant system", "Quarantine mint token", "DENY"],
          ["INV-6-31", "Worker identity is ephemeral and execution-specific. Reuse after DESTROY is prohibited and MUST be rejected.", "Reuse workerId after DESTROY", "DENY"],
          ["INV-6-32", "The Execution Broker does not establish the isolated execution environment. Isolation Guard must successfully create and bind before execution is permitted.", "Admit without bind-allow", "DENY"],
          ["INV-6-33", "Network access is default-deny. Metadata, localhost, internal services, and destinations not explicitly admitted MUST be denied.", "Unadmitted metadata/localhost", "DENY/CONTAIN"],
          ["INV-6-34", "A Worker cannot verify its own consequential execution. Worker identity and Verification Agent identity MUST remain distinct.", "Worker self-verify", "DENY as verification"],
        ],
      },
      { k: "h", t: "Failure matrix", l: 2 },
      {
        k: "table",
        cols: ["Failure", "Required outcome"],
        rows: [
          ["Broker bypass / alternative path", "DENY"],
          ["Missing authority / missing capability / capability > authority", "DENY"],
          ["Isolation unavailable / Guard bind-deny / Broker as jail", "DENY"],
          ["Unadmitted metadata / localhost / internal net", "DENY / CONTAIN"],
          ["Worker identity reuse after DESTROY", "DENY"],
          ["Worker self-verify", "DENY as verification"],
          ["Production direct access", "DENY"],
          ["Wrong tenant / product / environment / resource", "DENY"],
          ["Resource limit exceeded / timeout / runaway", "HALT / CONTAIN"],
          ["Sandbox/container/FS escape / secret boundary / exfil", "HALT / QUARANTINE / AUDIT"],
          ["Unauthorized network egress", "DENY / CONTAIN"],
          ["Revocation during execution", "HALT / CONTAIN"],
          ["Queue stale / retry exceeds bound / recursive over-scope", "DENY / HALT"],
          ["Quarantine bypass", "DENY"],
          ["Audit or monitor failure", "Fail-safe DENY/HALT — no silent continue"],
          ["Broker unavailable", "DENY for consequential execution"],
          ["Unclassified consequential execution", "DENY"],
          ["Emergency unrestricted prod", "DENY"],
        ],
      },
    ],
  ),

  s(
    "a6trace",
    "IX.T",
    "Art. 6 Trace",
    "Article 6 — traceability, compatibility, open issues",
    "LOCKED. Compact A.3 unchanged. Article 7 drafted separately — not this Article.",
    [
      {
        k: "p",
        t: "Article 6 → P6 (primary; also P1, P4, P5, P13, P15; not bijective) → Authority System + Capability System (preconditions) → Trust Kernel (floor) → Execution Broker (admit/refuse/interrupt; does not create jail) → Isolation Guard (CREATE + BIND) → Worker (ephemeral RUN) → EXTRACT → DESTROY → network/secret/resource bounds → quarantine → AuditEvent. No component is a grantor. Execution is not verification.",
      },
      { k: "h", t: "Compatibility (1–5 locked, unmodified)", l: 2 },
      {
        k: "table",
        cols: ["Article", "Result", "Note"],
        rows: [
          ["1 Human Sovereignty", "PASS", "Worker ≠ Human; ephemeral; emergency not prod bypass; quarantine not a grantor."],
          ["2 AGBOFA Sovereignty", "PASS", "Broker remains admission; Guard is jail, not issuer; IAM/container ≠ grant."],
          ["3 Intelligence ≠ authority", "PASS", "Intelligence may request; not unrestricted exec."],
          ["4 Authority Is Explicit", "PASS", "Admit still requires live chain; isolation cannot repair a missing chain."],
          ["5 Capability Is Scoped", "PASS", "Admit still requires cap ≤ grant; escape ≠ grant; net default-deny within token."],
        ],
      },
      { k: "h", t: "Implementation boundary", l: 2 },
      {
        k: "p",
        t: "Law defines the required boundary. It does not prove the sandbox is secure. SPECIFIED — RUNTIME IMPLEMENTATION PENDING. Not claimed: container/VM/process isolation operational, kernel hardening, network enforcement, secret management, resource/timeout enforcement, production controls, quarantine implementation, Broker/Guard runtime, M4/M5, Day-30, production or security certification. Four corrections are constitutional text, not runtime proof.",
      },
      { k: "h", t: "Open issues / handoffs", l: 2 },
      {
        k: "table",
        cols: ["Issue", "Belongs to"],
        rows: [
          ["Container/cgroup/network policy encoding", "Implementation"],
          ["Numeric resource quotas per risk class", "Implementation / policy"],
          ["Quarantine release workflow UX", "Implementation; still Arts. 1–5 for release authority"],
          ["Partial execution vs correctness", "Article 7 when authorized (6.8 already HALT; not success)"],
          ["Token encoding / LOW offline window", "Art. 5 implementation carry-forward"],
          ["Dual-control / federation", "Art. 1 / Art. 2 unchanged"],
        ],
      },
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Article 6 is constitutionally settled unless formally amended. Compact A.3 unchanged. Articles 1–5 unchanged. Four corrections closed. ATK-6-01–54 and INV-6-01–34 accepted. Runtime SPECIFIED — RUNTIME IMPLEMENTATION PENDING. No container, Day-30, M4/M5, or production certification is claimed. Reader ≠ platform.",
      },
    ],
  ),
];
