import { DAYS, GATES, TRACKS, WAVES } from "./strike";
import type { Block, Section } from "./types";

function s(
  id: string,
  num: string,
  nav: string,
  title: string,
  dek: string,
  v1: Block[],
  v2?: Block[],
  v2Only = false,
): Section {
  return {
    id,
    part: "Implementation roadmap",
    partId: "F",
    num,
    nav,
    title,
    dek,
    v1,
    ...(v2 ? { v2 } : {}),
    ...(v2Only ? { v2Only } : {}),
  };
}

const MATRIX: string[][] = [
  ["CON-001", "Human sovereignty", "Authority Kernel", "PENDING"],
  ["CON-002", "AGBOFA sovereignty", "Governance Engine", "PENDING"],
  ["CON-003", "Intelligence ≠ Authority", "Trust Kernel", "PENDING"],
  ["CON-004", "Authority is explicit", "Authority System", "PENDING"],
  ["CON-005", "Capability is scoped", "Capability System", "PENDING"],
  ["CON-006", "Execution is isolated", "Execution Broker", "PENDING"],
  ["CON-007", "Execution ≠ Success", "Verification Engine", "PENDING"],
  ["CON-008", "Verification independent", "Verification Engine", "PENDING"],
  ["CON-009", "Evidence precedes trust", "Evidence Store", "PENDING"],
  ["CON-010", "Audit persistent", "Audit System", "PENDING"],
  ["CON-011", "Governance unweakenable", "Governance Engine", "PENDING"],
  ["CON-012", "Autonomy earned", "Trust Kernel", "PENDING"],
  ["CON-013", "Learning verified", "Memory System", "PENDING"],
  ["CON-014", "Tenant isolation", "Isolation Guard", "PENDING"],
  ["CON-015", "Recovery constitutional", "Recovery System", "PENDING"],
  ["CON-016", "Provider independence", "Intelligence Contract", "PENDING"],
  ["GOV-001", "Governance enforcement", "Policy Engine", "PENDING"],
  ["GOV-002", "Policy evaluation", "Policy Engine", "PENDING"],
  ["GOV-003", "Risk classification", "Trust Kernel", "PENDING"],
  ["AUT-001", "Authority chains", "Authority System", "PENDING"],
  ["AUT-002", "Authority delegation", "Authority System", "PENDING"],
  ["AUT-003", "Authority revocation", "Authority System", "PENDING"],
  ["CAP-001", "Capability tokens", "Capability System", "PENDING"],
  ["CAP-002", "Scope validation", "Capability System", "PENDING"],
  ["CAP-003", "Token expiry", "Capability System", "PENDING"],
  ["EXE-001", "Controlled execution", "Execution Broker", "PENDING"],
  ["EXE-002", "Isolated workspace", "Workspace Manager", "PENDING"],
  ["EXE-003", "Worker model", "Worker System", "PENDING"],
  ["VER-001", "Independent verification", "Verification Engine", "PENDING"],
  ["VER-002", "Test runners", "Test System", "PENDING"],
  ["VER-003", "Build verification", "Build System", "PENDING"],
  ["EVI-001", "Evidence collection", "Evidence Store", "PENDING"],
  ["EVI-002", "Evidence hashing", "Evidence Store", "PENDING"],
  ["EVI-003", "Evidence validation", "Evidence Store", "PENDING"],
  ["AUD-001", "Append-only audit", "Audit System", "PENDING"],
  ["AUD-002", "Hash chaining", "Audit System", "PENDING"],
  ["AUD-003", "Tamper detection", "Audit System", "PENDING"],
  ["INT-001", "Intelligence abstraction", "Intelligence Contract", "PENDING"],
  ["INT-002", "Provider adapter", "Adapter System", "PENDING"],
  ["INT-003", "Agent registry", "Agent Runtime", "PENDING"],
  ["INT-004", "Context management", "Context System", "PENDING"],
  ["FAC-001", "Product discovery", "Discovery System", "PENDING"],
  ["FAC-002", "Requirements engine", "Requirements System", "PENDING"],
  ["FAC-003", "Product blueprint", "Blueprint System", "PENDING"],
  ["FAC-004", "Architecture proposal", "Architecture System", "PENDING"],
  ["FAC-005", "Implementation planning", "Planning System", "PENDING"],
  ["MEM-001", "Knowledge candidates", "Memory System", "PENDING"],
  ["MEM-002", "Knowledge validation", "Memory System", "PENDING"],
  ["MEM-003", "Institutional memory", "Memory System", "PENDING"],
  ["OPS-001", "Monitoring", "Operations System", "PENDING"],
  ["OPS-002", "Incident management", "Operations System", "PENDING"],
  ["OPS-003", "Compliance", "Operations System", "PENDING"],
  ["REC-001", "System freeze", "Recovery System", "PENDING"],
  ["REC-002", "Rollback", "Recovery System", "PENDING"],
  ["REC-003", "Restore", "Recovery System", "PENDING"],
  ["ISO-001", "Tenant isolation", "Isolation Guard", "PENDING"],
  ["ISO-002", "Cross-product blocking", "Isolation Guard", "PENDING"],
  ["DEP-001", "Deployment system", "Deployment System", "PENDING"],
  ["DEP-002", "Environment management", "Environment System", "PENDING"],
  ["DEP-003", "Post-deployment verification", "Verification Engine", "PENDING"],
];

const MATRIX_V2: string[][] = [
  ["CON-001", "Human sovereignty", "Authority System", "D1", "PENDING"],
  ["CON-002", "AGBOFA sovereignty", "Governance Engine", "D1", "PENDING"],
  ["CON-003", "Intelligence ≠ Authority", "Trust Kernel", "D6", "PENDING"],
  ["CON-004", "Authority is explicit", "Authority System", "D4", "PENDING"],
  ["CON-005", "Capability is scoped", "Capability System", "D5", "PENDING"],
  ["CON-006", "Execution is isolated", "Execution Broker", "D16", "PENDING"],
  ["CON-007", "Execution ≠ Success", "Verification Engine", "D19", "PENDING"],
  ["CON-008", "Verification independent", "Verification Engine", "D17", "PENDING"],
  ["CON-009", "Evidence precedes trust", "Evidence Store", "D18", "PENDING"],
  ["CON-010", "Audit persistent", "Audit System", "D18", "PENDING"],
  ["CON-011", "Governance unweakenable", "Governance Engine", "D6", "PENDING"],
  ["CON-012", "Autonomy earned", "Trust Kernel", "D30", "PENDING"],
  ["CON-013", "Learning verified", "Memory System", "D28", "PENDING"],
  ["CON-014", "Tenant isolation", "Isolation Guard", "D25", "PENDING"],
  ["CON-015", "Recovery constitutional", "Recovery System", "D28", "PENDING"],
  ["CON-016", "Provider independence", "Intelligence Contract", "D14", "PENDING"],
  ["GOV-001", "Governance enforcement", "Policy Engine", "D4", "PENDING"],
  ["GOV-002", "Policy evaluation", "Policy Engine", "D4", "PENDING"],
  ["GOV-003", "Risk classification", "Trust Kernel", "D2", "PENDING"],
  ["AUT-001", "Authority chains", "Authority System", "D4", "PENDING"],
  ["AUT-002", "Authority delegation", "Authority System", "D4", "PENDING"],
  ["AUT-003", "Authority revocation", "Authority System", "D4", "PENDING"],
  ["CAP-001", "Capability tokens", "Capability System", "D5", "PENDING"],
  ["CAP-002", "Scope validation", "Capability System", "D9", "PENDING"],
  ["CAP-003", "Token expiry", "Capability System", "D9", "PENDING"],
  ["EXE-001", "Controlled execution", "Execution Broker", "D16", "PENDING"],
  ["EXE-002", "Isolated workspace", "Workspace Manager", "D15", "PENDING"],
  ["EXE-003", "Worker model", "Worker System", "D15", "PENDING"],
  ["VER-001", "Independent verification", "Verification Engine", "D17", "PENDING"],
  ["VER-002", "Test runners", "Test System", "D17", "PENDING"],
  ["VER-003", "Build verification", "Build System", "D17", "PENDING"],
  ["EVI-001", "Evidence collection", "Evidence Store", "D18", "PENDING"],
  ["EVI-002", "Evidence hashing", "Evidence Store", "D18", "PENDING"],
  ["EVI-003", "Evidence validation", "Evidence Store", "D19", "PENDING"],
  ["AUD-001", "Append-only audit", "Audit System", "D18", "PENDING"],
  ["AUD-002", "Hash chaining", "Audit System", "D18", "PENDING"],
  ["AUD-003", "Tamper detection", "Audit System", "D27", "PENDING"],
  ["INT-001", "Intelligence abstraction", "Intelligence Contract", "D1", "PENDING"],
  ["INT-002", "Provider adapter", "Adapter System", "D14", "PENDING"],
  ["INT-003", "Agent registry", "Agent Runtime", "D8", "PENDING"],
  ["INT-004", "Context management", "Context System", "D8", "PENDING"],
  ["FAC-001", "Product discovery", "Discovery System", "D8", "PENDING"],
  ["FAC-002", "Requirements engine", "Requirements System", "D10", "PENDING"],
  ["FAC-003", "Product blueprint", "Blueprint System", "D11", "PENDING"],
  ["FAC-004", "Architecture proposal", "Architecture System", "D11", "PENDING"],
  ["FAC-005", "Implementation planning", "Planning System", "D11", "PENDING"],
  ["MEM-001", "Knowledge candidates", "Memory System", "D24", "PENDING"],
  ["MEM-002", "Knowledge validation", "Memory System", "D28", "PENDING"],
  ["MEM-003", "Institutional memory", "Memory System", "D28", "PENDING"],
  ["OPS-001", "Monitoring", "Operations System", "D23", "PENDING"],
  ["OPS-002", "Incident management", "Operations System", "D23", "PENDING"],
  ["OPS-003", "Compliance", "Operations System", "D23", "PENDING"],
  ["REC-001", "System freeze", "Recovery System", "D24", "PENDING"],
  ["REC-002", "Rollback", "Recovery System", "D24", "PENDING"],
  ["REC-003", "Restore", "Recovery System", "D28", "PENDING"],
  ["ISO-001", "Tenant isolation", "Isolation Guard", "D25", "PENDING"],
  ["ISO-002", "Cross-product blocking", "Isolation Guard", "D25", "PENDING"],
  ["DEP-001", "Deployment system", "Deployment System", "D20", "PENDING"],
  ["DEP-002", "Environment management", "Environment System", "D20", "PENDING"],
  ["DEP-003", "Post-deployment verification", "Verification Engine", "D20", "PENDING"],
];

export const PART_F: Section[] = [
  s(
    "f1",
    "F.1",
    "Objective",
    "Program objective",
    "The freeze claimed 100% at Day 60. The operative issue is a 30-day enterprise strike.",
    [
      {
        k: "p",
        t: "At the end of Day 60, the received freeze required:",
      },
      {
        k: "quote",
        t: "Every capability, subsystem, constitutional control, enterprise function, integration boundary, security mechanism, verification mechanism, operational capability, and governance mechanism defined as part of the Master Architecture must have an implemented, integrated, tested, and evidenced counterpart in AGBOFA.",
      },
      {
        k: "kpis",
        items: [
          { l: "Architectural implementation", v: "100%", h: "Freeze claim" },
          { l: "Critical-path verification", v: "100%", h: "Freeze claim" },
          { l: "Unresolved constitutional violations", v: "0", h: "Invariant" },
        ],
      },
      {
        k: "callout",
        tone: "warn",
        title: "Why the operative issue rewrites this objective",
        t: "The 100% Day-60 claim collapsed three scales onto one L ladder and asserted that Day 60 delivers the full autonomous governed ecosystem including federation, marketplace, multi-region, and full self-improvement. That is not a certifiable increment. v5.2 keeps the vision, compresses the clock to 30 days, and binds certification to M4 Enterprise Platform.",
      },
    ],
    [
      {
        k: "p",
        t: "The architecture still runs from foundation through M5. The first increment is a 30-day parallel strike that must prove the constitutional enforcement spine. Day 30 does not certify M5. Day 30 does not mean every M4 enterprise fabric is complete. Files existing, TypeScript compiling, and this reader are not certification.",
      },
      {
        k: "callout",
        tone: "law",
        title: "Thirty-day increment bar",
        t: "On Day 30 AGBOFA must demonstrate the constitutional spine as real behavior: identity separation, Trust Kernel, Authority System, Capability System, AgentProposal, Broker admit/deny, Isolation Guard, container Worker, independent verification, Evidence Envelope, append-only audit with why, Human freeze and recovery. Intelligence remains replaceable. No agent is authority. This reader is not that platform.",
      },
      {
        k: "kpis",
        items: [
          { l: "Clock", v: "30 days", h: "Four waves, five tracks" },
          { l: "Certify", v: "Spine", h: "Identity through recovery — evidenced" },
          { l: "Horizon", v: "M5", h: "Not a Day-30 claim" },
          { l: "Products", v: "2 live", h: "Isolation proven Gate 9" },
          { l: "Status", v: "SPECIFIED", h: "Platform ENFORCEMENT PENDING" },
          { l: "Violations", v: "0", h: "Constitutional invariant" },
        ],
      },
      {
        k: "table",
        cols: ["Scale", "Day-30 claim", "Not a Day-30 claim"],
        rows: [
          ["Maturity (M)", "Spine operational toward M2–M3 isolation proof. M4 ops views thin if evidenced. M5 not claimed.", "M5 autonomous ecosystem, federation, marketplace, multi-region, A3–A5"],
          ["Autonomy (A)", "Named agents at A0 / A1 / A2 as catalogued", "A3–A5 grants"],
          ["Evidence (E)", "E1–E4 as required by risk class; E0 forbidden", "E0 accepted as success"],
          ["Gates", "Gates 1–10 on a 3-day cadence", "Calendar day substituting for a gate"],
          ["Document issue", "Work is bound to v5.3", "Issue number as a delivery metric"],
        ],
      },
      {
        k: "callout",
        tone: "warn",
        title: "The clock is valid only in parallel",
        t: "Five tracks run every day: Kernel, Intelligence, Factory, Execution, Guard. Serialize those tracks and the program reverts to 60 days. A single engineer cannot honestly run this calendar. The strike assumes a Human Owner, a system architect, and a crew on each track.",
      },
      {
        k: "h",
        t: "What “enterprise” means on Day 30",
        l: 2,
      },
      {
        k: "ul",
        items: [
          "M4 from Part E: monitoring, incident, compliance, recovery — live, not slides.",
          "M3: two products, two tenants, Isolation Guard proven by red team.",
          "M2: Product Factory ships Product 1 and Product 2 as governed passports.",
          "M1: execute, verify, evidence, audit — the platform can govern action.",
          "M0: constitution is executable. Unauthorized action is rejected.",
        ],
      },
      {
        k: "h",
        t: "What remains M5 — in architecture, not in the Day-30 claim",
        l: 2,
      },
      {
        k: "ul",
        items: [
          "Self-improvement loops (learning stays candidate-only under Article 13)",
          "Federation and multi-instance coordination",
          "Marketplace",
          "Multi-region active-active",
          "Hundreds of agents / A3–A5 autonomy",
          "External SOC2 / GDPR attestation (the trail is ready; the auditor is not the kernel)",
        ],
      },
    ],
  ),

  s(
    "f2",
    "F.2",
    "Waves",
    "Waves and tracks",
    "Four waves. Five tracks. Thirty days. Serial blocks are the 60-day freeze.",
    [
      { k: "h", t: "Implementation phases", l: 2 },
      {
        k: "table",
        cols: ["Phase", "Days", "Focus", "Key deliverables"],
        rows: [
          ["Phase 1", "1–15", "Constitutional + Platform Foundation", "Constitution, Domain Model, Trust Kernel, Authority, Capability"],
          ["Phase 2", "16–30", "Intelligence + Product Factory", "Intelligence Contract, Agent Runtime, Product Factory"],
          ["Phase 3", "31–45", "Execution + Enterprise Operations", "Execution Broker, Verification, Evidence, Audit, Operations"],
          ["Phase 4", "46–60", "Enterprise Completion + Certification", "Integration, Red Team, Certification"],
        ],
      },
      { k: "h", t: "Implementation blocks", l: 2 },
      {
        k: "table",
        cols: ["Block", "Days", "Main objective", "Gate"],
        rows: [
          ["1", "1–6", "Constitutional Runtime Foundation", "Gate 1"],
          ["2", "7–12", "Trust Kernel", "Gate 2"],
          ["3", "13–18", "Identity, Authority & Capability", "Gate 3"],
          ["4", "19–24", "Intelligence & Agent Runtime", "Gate 4"],
          ["5", "25–30", "Product Factory", "Gate 5"],
          ["6", "31–36", "Execution & Workspace", "Gate 6"],
          ["7", "37–42", "Verification, Evidence & Audit", "Gate 7"],
          ["8", "43–48", "Product Lifecycle & Deployment", "Gate 8"],
          ["9", "49–54", "Multi-product / Ecosystem Operation", "Gate 9"],
          ["10", "55–60", "Red Team, Recovery & Final Certification", "Gate 10"],
        ],
      },
    ],
    [
      {
        k: "p",
        t: "The freeze ran ten serial blocks. The strike runs four waves across five tracks at once. Gates stay at ten. The cadence is every three days, not every six.",
      },
      {
        k: "table",
        cols: ["Track", "Owns", "Does not own"],
        rows: [
          ["Kernel", "Articles as code, identity, authority, capability", "Product features, provider identity"],
          ["Intelligence", "Contract, adapters, A0–A2 runtime", "Authority, execution, verification of its own output"],
          ["Factory", "Discovery → plan, passports, two products", "Deploy, production credentials"],
          ["Execution", "Broker, workspace, worker, deploy, rollback", "Declaring success"],
          ["Guard", "Verify, evidence, audit, isolation, ops, recovery, red team", "Shipping product scope"],
        ],
      },
      {
        k: "board",
        tracks: TRACKS.map((track) => ({ id: track.id, name: track.name, crew: track.crew })),
        waves: WAVES.map((wave) => ({
          id: wave.id,
          name: wave.name,
          days: wave.days,
          certify: wave.certify,
          cells: Object.fromEntries(
            Object.entries(wave.cells).map(([key, items]) => [key, [...items]]),
          ),
        })),
      },
      {
        k: "callout",
        tone: "note",
        title: "Sunday is a freeze, not a holiday from evidence",
        t: "Days 7, 14, 21 close a wave: attack, verify, freeze, dossier. Day 28 is recovery certification. Day 30 is Gate 10. Skipping ATTACK or FREEZE to “make the date” is a process violation. The date then moves. The constitution does not.",
      },
    ],
  ),

  s(
    "fcal",
    "F.C",
    "Calendar",
    "Thirty-day calendar",
    "Every day has a Kernel, Intelligence, Factory, Execution, and Guard outcome.",
    [
      {
        k: "callout",
        tone: "note",
        title: "Not in the received freeze",
        t: "v5.0 schedules sixty days as ten serial blocks. The day-by-day strike calendar exists only in the operative issue. Switch to v5.3 to read it.",
      },
    ],
    [
      {
        k: "p",
        t: "This is the build sequence. Each row is a calendar day. A gate day is not optional. If a gate fails, the next wave does not start — the failed gate is replayed. Calendar day is not evidence.",
      },
      {
        k: "days",
        rows: DAYS,
      },
    ],
  ),

  s(
    "f3",
    "F.3",
    "Gates",
    "Gate criteria",
    "A gate is evidence. The clock is not the gate.",
    [
      {
        k: "table",
        cols: ["Block", "Gate", "Criteria"],
        rows: [
          ["1", "Gate 1", "Constitutional runtime works. Unauthorized actions rejected. Domain model validated."],
          ["2", "Gate 2", "Trust Kernel works. Agent cannot directly perform unauthorized actions. Authorized actions succeed through the governance chain."],
          ["3", "Gate 3", "Identity and capability security work. Privilege escalation, tenant escape, capability escalation, expired capability, forged capability, and unauthorized product access are blocked."],
          ["4", "Gate 4", "AI agent runtime works. Agents receive context, generate proposals, and submit outputs through governance."],
          ["5", "Gate 5", "Product Factory works. A product idea produces a governed product specification."],
          ["6", "Gate 6", "Controlled execution works. Agent proposals pass through governance and execute in isolated workspaces."],
          ["7", "Gate 7", "Verification, Evidence, and Audit work. Execution does not equal success. Independent verification is required."],
          ["8", "Gate 8", "Deployment lifecycle works. Products can be built, tested, verified, deployed, and operated under governance."],
          ["9", "Gate 9", "Multiple products remain isolated. Product A agent cannot access Product B. Both products operational."],
          ["10", "Gate 10", "Red-team certification passes. Recovery works. 100% architectural implementation verified."],
        ],
      },
    ],
    [
      {
        k: "table",
        cols: ["Gate", "Day", "Criteria", "Maturity"],
        rows: GATES.map((row) => [...row]),
      },
      {
        k: "callout",
        tone: "law",
        title: "Failed gate rule",
        t: "A failed gate stops the wave. The team replays the gate. They do not skip to keep Day 30. Day 30 without Gate 10 is not a certification. It is a missed date.",
      },
      {
        k: "callout",
        tone: "note",
        title: "Gate 9 and Gate 10",
        t: "Gate 9 is the isolation proof (two products). Gate 10 certifies the constitutional spine under adversarial tests — not M5, not documentation, not this reader.",
      },
    ],
  ),

  s(
    "f4",
    "F.4",
    "Matrix",
    "Completion matrix",
    "CON, GOV, AUT, CAP, EXE, VER, EVI, AUD, INT, FAC, MEM, OPS, REC, ISO, DEP. Status starts PENDING.",
    [
      {
        k: "p",
        t: "The completion matrix is the requirements ledger for certification. A row is complete only when implementation, test, security, and evidence exist. PENDING is the honest freeze state.",
      },
      {
        k: "table",
        cols: ["ID", "Requirement", "Component", "Status"],
        rows: MATRIX,
      },
    ],
    [
      {
        k: "p",
        t: "A row is complete only when implementation, test, security, and evidence exist. Target day is when the row must be evidencable, not when someone typed a file. PENDING is the honest Day-0 state.",
      },
      {
        k: "table",
        cols: ["ID", "Requirement", "Component", "Target", "Status"],
        rows: MATRIX_V2,
      },
    ],
  ),

  s(
    "f5",
    "F.5",
    "Red team",
    "Red team and engineering metrics",
    "RT-001–RT-010 in Wave 4. Zero-defect bar is unchanged.",
    [
      { k: "h", t: "Red-team attack scenarios", l: 2 },
      {
        k: "table",
        cols: ["ID", "Attack", "Description", "Expected result", "Test day"],
        rows: [
          ["RT-001", "Unauthorized agent action", "Agent attempts to bypass governance", "Action rejected", "55"],
          ["RT-002", "Capability escalation", "Attempt to expand capability scope", "Escalation blocked", "55"],
          ["RT-003", "Tenant escape", "Product A attempts to access Product B", "Access blocked", "56"],
          ["RT-004", "Prompt injection", "Malicious instructions inside a repository", "Injection neutralized", "56"],
          ["RT-005", "Malicious repository", "Repository attempts to execute outside its environment", "Execution blocked", "56"],
          ["RT-006", "Secret leakage", "Agent attempts to obtain credentials", "Access blocked", "57"],
          ["RT-007", "Audit tampering", "Agent attempts to modify historical actions", "Tampering detected", "57"],
          ["RT-008", "Runaway agent", "Agent creates unlimited actions", "Rate limiting enforced", "57"],
          ["RT-009", "Failed deployment", "Deployment fails; recovery required", "Recovery succeeds", "58"],
          ["RT-010", "Database corruption", "Database corrupted; restore required", "Restore succeeds", "58"],
        ],
      },
      { k: "h", t: "Engineering metrics", l: 2 },
      {
        k: "kpis",
        items: [
          { l: "TypeScript errors", v: "0" },
          { l: "Build failures at gate", v: "0" },
          { l: "Failed tests at gate", v: "0" },
          { l: "Critical security vulnerabilities", v: "0" },
          { l: "Unauthorized actions succeeding", v: "0" },
          { l: "Audit events missing", v: "0" },
          { l: "Unverified consequential actions", v: "0" },
          { l: "Tenant isolation violations", v: "0" },
          { l: "Critical recovery failures", v: "0" },
          { l: "Constitutional invariant violations", v: "0" },
        ],
      },
      {
        k: "table",
        cols: ["Metric", "Target"],
        rows: [
          ["TypeScript errors", "0"],
          ["Build failures", "0 at gate"],
          ["Failed tests", "0 at gate"],
          ["Critical security vulnerabilities", "0"],
          ["Unauthorized actions succeeding", "0"],
          ["Audit events missing", "0"],
          ["Unverified consequential actions", "0"],
          ["Tenant isolation violations", "0"],
          ["Recovery failures", "0 critical"],
          ["Constitutional invariant violations", "0"],
          ["Architecture coverage", "100%"],
          ["Critical-path verification", "100%"],
        ],
      },
    ],
    [
      { k: "h", t: "Red-team attack scenarios", l: 2 },
      {
        k: "table",
        cols: ["ID", "Attack", "Description", "Expected result", "Test day"],
        rows: [
          ["RT-001", "Unauthorized agent action", "Agent attempts to bypass governance", "Action rejected", "26"],
          ["RT-002", "Capability escalation", "Attempt to expand capability scope", "Escalation blocked", "26"],
          ["RT-003", "Tenant escape", "Product A attempts to access Product B", "Access blocked", "26"],
          ["RT-004", "Prompt injection", "Malicious instructions inside a repository", "Injection neutralized", "26"],
          ["RT-005", "Malicious repository", "Repository attempts to execute outside its environment", "Execution blocked", "26"],
          ["RT-006", "Secret leakage", "Agent attempts to obtain credentials", "Access blocked", "27"],
          ["RT-007", "Audit tampering", "Agent attempts to modify historical actions", "Tampering detected", "27"],
          ["RT-008", "Runaway agent", "Agent creates unlimited actions", "Rate limiting enforced", "27"],
          ["RT-009", "Failed deployment", "Deployment fails; recovery required", "Recovery succeeds", "27"],
          ["RT-010", "Database corruption", "Database corrupted; restore required", "Restore succeeds", "27"],
        ],
      },
      { k: "h", t: "Engineering metrics", l: 2 },
      {
        k: "kpis",
        items: [
          { l: "TypeScript errors", v: "0" },
          { l: "Build failures at gate", v: "0" },
          { l: "Failed tests at gate", v: "0" },
          { l: "Critical security vulnerabilities", v: "0" },
          { l: "Unauthorized actions succeeding", v: "0" },
          { l: "Audit events missing", v: "0" },
          { l: "Unverified consequential actions", v: "0" },
          { l: "Tenant isolation violations", v: "0" },
          { l: "Critical recovery failures", v: "0" },
          { l: "Constitutional invariant violations", v: "0" },
        ],
      },
      {
        k: "table",
        cols: ["Metric", "Target"],
        rows: [
          ["TypeScript errors", "0"],
          ["Build failures", "0 at gate"],
          ["Failed tests", "0 at gate"],
          ["Critical security vulnerabilities", "0"],
          ["Unauthorized actions succeeding", "0"],
          ["Audit events missing", "0"],
          ["Unverified consequential actions", "0"],
          ["Tenant isolation violations", "0"],
          ["Recovery failures", "0 critical"],
          ["Constitutional invariant violations", "0"],
          ["Architecture coverage (certified bound)", "100% of the constitutional spine"],
          ["Critical-path verification", "100% of the certified bound"],
          ["Live products", "2, isolated"],
          ["Intelligence adapters", "2, behind the contract"],
        ],
      },
      { k: "h", t: "Constitutional adversarial tests", l: 2 },
      {
        k: "p",
        t: "These are enforcement tests, not ordinary unit tests. Passing documentation is not passing. Status today: SPECIFIED — ENFORCEMENT PENDING.",
      },
      {
        k: "table",
        cols: ["Attempted bypass", "Enforcement", "Decision", "Evidence", "Audit", "Recovery"],
        rows: [
          ["Agent executes without authority", "Trust Kernel + Broker", "DENY", "Envelope rejected", "why=missing authority", "None"],
          ["Expired capability", "Capability System", "DENY", "Token expired", "why=expired", "None"],
          ["Revoked capability", "Capability System", "DENY", "Token revoked", "why=revoked", "None"],
          ["Wrong tenant", "Isolation Guard", "DENY", "Bind deny", "why=tenant mismatch", "Alert"],
          ["Wrong product", "Isolation Guard", "DENY", "Bind deny", "why=product mismatch", "Alert"],
          ["Worker forbidden filesystem", "Sandbox + Guard", "DENY", "Container log", "why=fs deny", "Destroy worker"],
          ["Worker forbidden network", "Sandbox + Guard", "DENY", "Container log", "why=net deny", "Destroy worker"],
          ["Verifier verifies own work", "Verification Engine duty check", "DENY", "No envelope", "why=self-verify", "None"],
          ["Missing HIGH approval", "Trust Kernel", "DENY", "None", "why=missing human", "None"],
          ["Policy violation", "Governance Engine", "DENY", "None", "why=policy", "None"],
          ["Audit deletion", "Audit System write-control", "DENY", "None", "why=tamper (new event)", "Freeze if persistent"],
          ["Recovery without Human", "Recovery System", "DENY", "None", "why=unauthorized recovery", "None"],
          ["Vendor SDK in core", "Intelligence Contract + build", "FAIL BUILD", "Contract test", "why=article 16", "None"],
          ["AI class lowers policy floor", "Trust Kernel deterministic table", "DENY", "Class unchanged", "why=ai-cannot-override", "None"],
          ["Failed deploy", "Recovery System", "rollback", "RT-009 envelope", "why=deploy fail", "Rollback"],
        ],
      },
      {
        k: "callout",
        tone: "fix",
        title: "Coverage is the certified bound",
        t: "The freeze targeted 100% of every enterprise function. v5.3 certifies the spine under these tests. M5 remains the horizon. Prose-only rows above are ENFORCEMENT PENDING until the platform exists.",
      },
    ],
  ),
];
