import type { Block, Section } from "./types";

function s(
  id: string,
  num: string,
  nav: string,
  title: string,
  dek: string,
  v2: Block[],
): Section {
  return {
    id,
    part: "Constitution",
    partId: "A",
    num,
    nav,
    title,
    dek,
    v1: [
      {
        k: "callout",
        tone: "note",
        title: "Phase 9 Article 9 deep draft is not in the received freeze",
        t: "Compact Article 9 in A.3 remains the short form. Articles 1–8 are LOCKED. Switch to the operative issue.",
      },
    ],
    v2,
  };
}

export const PHASE9_A9: Section[] = [
  s(
    "ph9",
    "XII.0",
    "Phase 9",
    "Phase 9 — Article 9 draft status",
    "Evidence Precedes Trust. LOCKED — HUMAN ACCEPTED.",
    [
      {
        k: "callout",
        tone: "law",
        title: "Authoritative Article 9 subject",
        t: "v5.3 compact title is Article 9 — Evidence Precedes Trust. Compact A.3 unchanged. Articles 1–8 LOCKED / UNCHANGED. Article 9 LOCKED / HUMAN ACCEPTED under Owner authorization 2026-09-05 at 9472356 baseline. Runtime: SPECIFIED — RUNTIME IMPLEMENTATION PENDING. Reader ≠ platform. Version v5.3. No v5.4.",
      },
      {
        k: "table",
        cols: ["Phase", "Article", "Status"],
        rows: [
          ["Phase 1–8", "Articles 1–8", "LOCKED / HUMAN ACCEPTED — UNCHANGED"],
          ["Phase 9", "Article 9", "LOCKED / HUMAN ACCEPTED"],
          ["Phase 10", "Article 10", "LOCKED / HUMAN ACCEPTED"],
        ],
      },
    ],
  ),

  s(
    "a9law",
    "XII",
    "Art. 9 Law",
    "Article 9 — Evidence Precedes Trust (law)",
    "Evidence is attributable and bound. Evidence ≠ truth, authority, or SUCCESS. LOCKED.",
    [
      {
        k: "callout",
        tone: "note",
        title: "A.3 compact form — not replaced",
        t: "A.3 Article 9 remains Evidence Precedes Trust. This draft operationalizes attribution, binding, integrity, staleness, and the rule that evidence cannot mint authority or SUCCESS. Canonical object remains EvidenceEnvelope. No competing envelope. Article 10 audit is not drafted here.",
      },
      { k: "h", t: "9.1 Purpose", l: 2 },
      {
        k: "p",
        t: "Evidence is a governed record supporting a claim or verification outcome. Evidence is not automatically truth, correctness, safety, authorization, or SUCCESS. DATA ≠ CLAIM ≠ ARTIFACT ≠ OBSERVATION ≠ EVIDENCE ≠ VERIFICATION ≠ SUCCESS.",
      },
      { k: "h", t: "9.2 Constitutional rule", l: 2 },
      {
        k: "p",
        t: "Every consequential verification outcome and every consequential lifecycle transition that depends upon evidence shall be supported by evidence attributable to the correct execution, subject, tenant, product, environment, authority chain, capability scope, and verification context. Evidence that is missing, ambiguous, stale, forged, cross-bound, unverifiable, improperly attributed, or outside its authorized scope shall not establish SUCCESS or authorize the next consequential lifecycle stage. Evidence supports determination. Evidence does not create authority, enlarge capability, bypass verification, or rewrite history.",
      },
      { k: "h", t: "9.3 Distinctions", l: 2 },
      {
        k: "table",
        cols: ["Term", "Meaning"],
        rows: [
          ["DATA", "Raw bytes or records. Not evidence until attributed and bound."],
          ["OBSERVATION / RAW RESULT", "e.g. build exited 0. Not SUCCESS."],
          ["CLAIM", "e.g. 'build is correct'. Compact: a claim without evidence is unverified."],
          ["ARTIFACT", "log, test, config, scan, image, diff, workspace_extract (existing Artifact). May become evidence; existence ≠ truth."],
          ["EVIDENCE", "Governed EvidenceEnvelope supporting a claim or verification."],
          ["VERIFICATION", "Article 8 independent determination. Evidence does not replace it."],
          ["SUCCESS", "Article 7 outcome. Evidence does not equal SUCCESS."],
        ],
      },
      { k: "h", t: "9.4 Canonical object", l: 2 },
      {
        k: "p",
        t: "The canonical evidence object is EvidenceEnvelope (v5.3 contracts): evidenceId, constitutionVersion, source (execution|verification|human|recovery|system), actor, tenantId, productId, proposalId, action, claim, result (pass|fail|unverified|rejected), timestamp, level (E1–E4; E0 never acceptable for a consequential claim), verificationStatus, verificationAgentId, artifacts[], parentEvidenceId, hash, previousHash, lifecycleStatus. No second evidence type. Constitutional binding to execution, environment, grant, and token must be representable without inventing a competing envelope (open implementation mapping — see gaps).",
      },
      { k: "h", t: "9.5 Levels preserved", l: 2 },
      {
        k: "p",
        t: "E0–E4 remain the only evidence taxonomy. E0 is never acceptable for a consequential claim. Higher level does not prove the claim is true; it records sufficiency class (existence/attribution/integrity/provenance/verification/decision). Compact: machine-verifiable where possible; stored in the Evidence Store with provenance.",
      },
    ],
  ),

  s(
    "a9bnd",
    "XII.C",
    "Art. 9 Bounds",
    "Article 9 — bind, integrity, staleness, lifecycle",
    "EvidenceEnvelope preserved. SPECIFIED — RUNTIME IMPLEMENTATION PENDING.",
    [
      { k: "h", t: "9.6 Attribution and bind", l: 2 },
      {
        k: "p",
        t: "Consequential evidence must answer: what produced it; for which subject; under which execution; under which authority; with which capability; in which tenant/product/environment; when; from which source; for which verification. Provider/agent/worker/human origin remains that origin after copy into AGBOFA. Copying does not transform provenance.",
      },
      { k: "h", t: "9.7 No silent cross-bound reuse", l: 2 },
      {
        k: "p",
        t: "Tenant A ↛ Tenant B SUCCESS. Product A ↛ Product B. Execution A ↛ Execution B. Environment A ↛ Environment B. Old deploy/commit ↛ new deploy/commit. One verification subject ↛ unrelated subject. Reuse only under explicit governed semantics. Implicit reuse DENY.",
      },
      { k: "h", t: "9.8 Temporal validity", l: 2 },
      {
        k: "p",
        t: "Historical evidence may describe historical state. It cannot silently establish current state when the relevant subject has changed (stale tests, scans, config, auth context, environment, replay after modification). No universal TTL is mandated; freshness is context-dependent and governed.",
      },
      { k: "h", t: "9.9 Integrity", l: 2 },
      {
        k: "p",
        t: "Consequential evidence requires integrity protection appropriate to risk: modification, deletion, truncation, replacement, forgery, fabricated timestamps, altered provenance/artifact refs, substituted artifacts, hash mismatch, broken chain. If required integrity cannot be established: DENY / REJECT / QUARANTINE. A hash proves correspondence to a protected representation, not semantic correctness.",
      },
      { k: "h", t: "9.10 Generated evidence", l: 2 },
      {
        k: "p",
        t: "An executor may produce artifacts, tests, reports, and envelopes. That is not independent verification (Art. 8). Executor-generated PASS is not verifier PASS. Generated evidence remains executor-sourced until independently verified.",
      },
      { k: "h", t: "9.11 Evidence ≠ authority / SUCCESS", l: 2 },
      {
        k: "p",
        t: "Evidence ≠ Human Authority ≠ Grant ≠ CapabilityToken ≠ Governance Decision ≠ Broker admission. History of success cannot authorize a future act or mint a token. Chain: COMPLETED → claim → independent verification → verification outcome → attributable bound evidence → Article 7 determination → SUCCESS. Evidence exists ↛ SUCCESS.",
      },
      { k: "h", t: "9.12 Lifecycle (not a second ExecutionState)", l: 2 },
      {
        k: "p",
        t: "CAPTURE → ATTRIBUTE → BIND → INTEGRITY CHECK → STORE → REFERENCE → VERIFY/CONSUME → RETAIN/EXPIRE/ARCHIVE. Lifecycle operations shall not rewrite FAILED→SUCCESS, UNVERIFIED→VERIFIED-PASS, or REJECTED→APPROVED.",
      },
      { k: "h", t: "9.13 Retention vs DESTROY", l: 2 },
      {
        k: "p",
        t: "Worker DESTROY (Art. 6) ≠ evidence destruction. Required evidence for a consequential decision survives ordinary execution cleanup. Unauthorized deletion, overwrite, destruction before verification or required retention, or loss of provenance: DENY as concealment. Rollback does not erase that execution/failure/verification/incident/rollback occurred. Recovery is not a deletion mechanism.",
      },
      { k: "h", t: "9.14 Access", l: 2 },
      {
        k: "p",
        t: "Evidence access is governed. Reading evidence does not confer execution authority, tenant authority, or capability. Cross-tenant evidence access must be explicit. Possession ≠ authority.",
      },
      { k: "h", t: "9.15 Evidence vs Audit", l: 2 },
      {
        k: "p",
        t: "Evidence supports a claim/observation/verification/outcome. Audit records governed events and constitutional history. An AuditEvent may reference evidenceId; an envelope is not an AuditEvent. Article 10 will specify write-control. Do not substitute one for the other.",
      },
    ],
  ),

  s(
    "a9adv",
    "XII.A",
    "Art. 9 Attack",
    "Article 9 — adversarial matrix",
    "ATK-9-01–30. Evidence ≠ SUCCESS. LOCKED.",
    [
      {
        k: "table",
        cols: ["ID", "Attack", "Boundary", "Detection (specified)", "Disposition", "Audit"],
        rows: [
          ["ATK-9-01", "Fabricated evidence", "9.9 provenance", "Integrity/issuer fail", "REJECT", "DENY + AUDIT"],
          ["ATK-9-02", "Forged provenance", "9.6", "Source/actor mismatch", "REJECT", "DENY + AUDIT"],
          ["ATK-9-03", "Wrong execution bind", "9.7", "execution mismatch", "REJECT", "Flag"],
          ["ATK-9-04", "Wrong tenant", "9.7", "tenantId", "REJECT", "Flag"],
          ["ATK-9-05", "Wrong product", "9.7", "productId", "REJECT", "Flag"],
          ["ATK-9-06", "Wrong environment", "9.7", "environment bind", "REJECT", "Flag"],
          ["ATK-9-07", "Stale replay", "9.8", "Subject changed", "Not current SUCCESS", "Flag"],
          ["ATK-9-08", "Old build as new build", "9.8 9.7", "Artifact/version", "REJECT", "Flag"],
          ["ATK-9-09", "Altered test output", "9.9", "Hash/chain", "REJECT/QUARANTINE", "AUDIT"],
          ["ATK-9-10", "Artifact modified after verify", "9.9 9.18", "Hash mismatch", "REJECT", "AUDIT"],
          ["ATK-9-11", "Hash mismatch", "9.9", "hash ≠ artifact", "REJECT", "AUDIT"],
          ["ATK-9-12", "Generated as independent verify", "9.10 Art. 8", "source=execution as VERIFIED-PASS", "Not independent", "Flag"],
          ["ATK-9-13", "Executor PASS as verifier PASS", "9.10", "actor=executor", "REJECT as verify", "Flag"],
          ["ATK-9-14", "Provider evidence as AGBOFA verify", "Art. 2 9.6", "source/provider", "Not AGBOFA verify", "Flag"],
          ["ATK-9-15", "Copy across tenants", "9.7 9.14", "tenantId", "DENY", "AUDIT"],
          ["ATK-9-16", "Copy across products", "9.7", "productId", "DENY", "AUDIT"],
          ["ATK-9-17", "Copy across environments", "9.7", "environment", "DENY", "AUDIT"],
          ["ATK-9-18", "Replay after rollback", "9.8 9.13", "Post-rollback subject", "Historical only", "Keep history"],
          ["ATK-9-19", "Delete before decision", "9.13", "Missing required", "UNVERIFIED/BLOCK", "AUDIT concealment"],
          ["ATK-9-20", "Overwrite", "9.12 9.16", "Silent mutate", "DENY", "AUDIT"],
          ["ATK-9-21", "Fabricated timestamp", "9.9", "Clock/provenance", "REJECT", "AUDIT"],
          ["ATK-9-22", "Partial as complete", "9.2", "Incomplete set", "INCONCLUSIVE/REJECT", "Flag"],
          ["ATK-9-23", "Contradictory resolved as SUCCESS", "9.2 Art. 7", "Conflict", "Not SUCCESS", "AUDIT"],
          ["ATK-9-24", "Corrupted accepted", "9.9 9.24", "Integrity fail", "REJECT/QUARANTINE", "AUDIT"],
          ["ATK-9-25", "Possession as authority", "9.11 9.14", "Read evidence", "Not a grant", "Flag"],
          ["ATK-9-26", "Audit substituted for evidence", "9.15", "AuditEvent as envelope", "REJECT as evidence", "Keep distinct"],
          ["ATK-9-27", "Evidence substituted for audit", "9.15", "Envelope as AuditEvent", "REJECT as audit", "Art. 10 later"],
          ["ATK-9-28", "Outside authorized execution", "9.2 Art. 6", "No admit/bind", "REJECT", "AUDIT"],
          ["ATK-9-29", "Unknown execution reference", "9.2", "Missing execution", "REJECT/UNVERIFIED", "Flag"],
          ["ATK-9-30", "Non-independent verifier", "Art. 8 9.10", "Same identity", "Not VERIFIED-PASS", "Flag"],
        ],
      },
    ],
  ),

  s(
    "a9inv",
    "XII.I",
    "Art. 9 Invariants",
    "Article 9 — invariants and failure matrix",
    "INV-9-00 master. LOCKED — HUMAN ACCEPTED. SPECIFIED — RUNTIME IMPLEMENTATION PENDING.",
    [
      {
        k: "table",
        cols: ["ID", "Invariant", "Test", "Expected"],
        rows: [
          ["INV-9-00", "Master: no evidence, regardless of source, provenance, integrity, persistence, quantity, confidence, consensus, or historical success, can by itself create, enlarge, transfer, or retain constitutional authority or establish consequential SUCCESS without satisfying applicable verification and outcome-determination requirements.", "Envelope alone → SUCCEEDED", "DENY"],
          ["INV-9-01", "Consequential evidence must be attributable.", "No actor/source", "REJECT"],
          ["INV-9-02", "Consequential evidence must remain bound to its subject.", "Unbound", "REJECT"],
          ["INV-9-03", "Cross-tenant reuse cannot occur without governed authorization.", "T1→T2", "DENY"],
          ["INV-9-04", "Cross-product reuse cannot silently establish SUCCESS.", "P1→P2", "DENY"],
          ["INV-9-05", "Cross-environment reuse cannot silently establish SUCCESS.", "ws→prod", "DENY"],
          ["INV-9-06", "Stale evidence cannot silently establish current state.", "Old scan after change", "Not current SUCCESS"],
          ["INV-9-07", "Integrity failure cannot establish SUCCESS.", "Hash fail", "REJECT/QUARANTINE"],
          ["INV-9-08", "Provenance cannot be fabricated.", "Altered source", "REJECT + AUDIT"],
          ["INV-9-09", "Generated evidence does not become independent verification.", "Executor suite as AG-VER", "Not independent"],
          ["INV-9-10", "Evidence does not create Human Authority.", "Envelope as grant", "DENY"],
          ["INV-9-11", "Evidence does not mint CapabilityTokens.", "PASS→token", "DENY"],
          ["INV-9-12", "Evidence does not enlarge capability.", "Report extra scope", "DENY extra"],
          ["INV-9-13", "Evidence does not replace Article 8 independence.", "Self-envelope", "Not VERIFIED-PASS"],
          ["INV-9-14", "Evidence does not replace Article 7 outcome determination.", "Exists → SUCCEEDED", "DENY"],
          ["INV-9-15", "Evidence cannot rewrite historical failure into success.", "Mutate result=fail→pass", "DENY + AUDIT"],
          ["INV-9-16", "Evidence cannot be silently overwritten where preservation is required.", "Overwrite", "DENY"],
          ["INV-9-17", "Evidence deletion cannot conceal a consequential event.", "Delete before decision", "UNVERIFIED/BLOCK + AUDIT"],
          ["INV-9-18", "Artifact identity must match the evidence claim where artifact binding is required.", "Wrong hash/uri", "REJECT"],
          ["INV-9-19", "Executor-generated evidence cannot self-establish consequential SUCCESS.", "Worker PASS", "Claim only"],
          ["INV-9-20", "Evidence access does not confer execution authority.", "Read envelope", "Not a grant"],
          ["INV-9-21", "Audit records and evidence remain distinct governed objects.", "Swap types", "REJECT"],
          ["INV-9-22", "Rollback does not erase historical evidence.", "Rollback deletes envelope", "DENY erasure"],
          ["INV-9-23", "Unknown or ambiguous binding cannot establish SUCCESS.", "Null subject", "REJECT"],
          ["INV-9-24", "Corruption produces rejection, quarantine, or other governed non-success.", "Corrupt store", "REJECT/QUARANTINE"],
          ["INV-9-25", "Evidence is support for determination, not constitutional authority or automatic truth.", "Treat as truth", "DENY that use"],
          ["INV-9-26", "E0 is never acceptable for a consequential claim.", "level=E0", "REJECT"],
          ["INV-9-27", "Absence of errors is not evidence of correctness.", "Empty error log", "Not SUCCESS"],
          ["INV-9-28", "Worker DESTROY does not destroy required governed evidence.", "Cleanup wipes store", "DENY"],
        ],
      },
      { k: "h", t: "Failure matrix", l: 2 },
      {
        k: "table",
        cols: ["Failure", "Required outcome"],
        rows: [
          ["Missing / malformed / ambiguous / unknown bind", "UNVERIFIED or REJECT; block promotion"],
          ["Wrong tenant/product/environment/execution", "REJECT"],
          ["Stale / replay after subject change", "Historical only; not current SUCCESS"],
          ["Integrity / forge / overwrite / concealment", "REJECT/QUARANTINE + AUDIT"],
          ["Generated / non-independent / provider-as-AGBOFA-verify", "Not independent verification"],
          ["E0 / absence-of-errors as correctness", "REJECT as consequential evidence"],
          ["Audit/evidence substitution; possession as authority", "DENY"],
          ["Contradiction silently resolved as SUCCESS", "Not SUCCESS"],
        ],
      },
    ],
  ),

  s(
    "a9trace",
    "XII.T",
    "Art. 9 Trace",
    "Article 9 — traceability, compatibility, open issues",
    "LOCKED — HUMAN ACCEPTED. Article 10 LOCKED separately.",
    [
      {
        k: "p",
        t: "Article 9 → P8 (evidence; not exclusive) also P5, P9, P13; not bijective → Evidence Store + EvidenceEnvelope (attribution, bind, hash chain, level E1–E4) → verification reference (Art. 8) → Article 7 SUCCESS determination → AuditEvent.evidenceId (Art. 10 later). Compact enforcement: claims lacking evidence marked unverified and cannot be used for decision-making.",
      },
      { k: "h", t: "Compatibility (1–8 locked, unmodified)", l: 2 },
      {
        k: "table",
        cols: ["Article", "Result", "Note"],
        rows: [
          ["1 Human Sovereignty", "PASS", "Evidence cannot create Human Authority."],
          ["2 AGBOFA Sovereignty", "PASS", "Provider evidence is not AGBOFA issuance or verification."],
          ["3 Intelligence ≠ authority", "PASS", "Generated evidence remains intelligence-originated until governed."],
          ["4 Authority Is Explicit", "PASS", "Evidence cannot substitute for a grant."],
          ["5 Capability Is Scoped", "PASS", "Evidence cannot enlarge tokens."],
          ["6 Execution Is Isolated", "PASS", "DESTROY ≠ evidence destruction."],
          ["7 Execution Is Not Success", "PASS", "Evidence supports, does not equal, SUCCESS."],
          ["8 Verification Is Independent", "PASS", "Evidence cannot replace independence."],
          ["10 Audit Is Persistent", "Constraint", "Not drafted; objects remain distinct."],
        ],
      },
      { k: "h", t: "Implementation boundary", l: 2 },
      {
        k: "p",
        t: "SPECIFIED — RUNTIME IMPLEMENTATION PENDING. Not claimed: EvidenceEnvelope runtime, Evidence Store, cryptographic provenance, hash enforcement, retention, replay detection, cross-tenant enforcement, AG-VER/AG-SECV running.",
      },
      { k: "h", t: "Open issues / handoffs", l: 2 },
      {
        k: "table",
        cols: ["Issue", "Belongs to"],
        rows: [
          ["EvidenceEnvelope first-class executionId / environmentId / grantId / tokenId", "Implementation mapping; do not invent a second envelope"],
          ["Append-only write-control, audit chain, history mutation", "Article 10 when authorized"],
          ["Numeric freshness SLOs per risk class", "Policy / implementation"],
          ["CRITICAL dual-control of evidence acceptance", "Article 1 potential amendment — not resolved here"],
        ],
      },
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Article 9 is constitutionally settled unless formally amended. Compact A.3 unchanged. Articles 1–8 unchanged. ATK-9-01–30 and INV-9-00–28 accepted as review material under this lock. Runtime SPECIFIED — RUNTIME IMPLEMENTATION PENDING. Reader ≠ platform. Evidence Store is not claimed running.",
      },
    ],
  ),
];
