import type { Block, Section } from "./types";

function s(
  id: string,
  num: string,
  nav: string,
  title: string,
  dek: string,
  v2: Block[],
): Section {
  return {
    id,
    part: "Constitution",
    partId: "A",
    num,
    nav,
    title,
    dek,
    v1: [
      {
        k: "callout",
        tone: "note",
        title: "Phase 4 Article 4 deep draft is not in the received freeze",
        t: "Compact Article 4 in A.3 remains the short form. Articles 1–3 are LOCKED. Switch to the operative issue.",
      },
    ],
    v2,
  };
}

export const PHASE4_A4: Section[] = [
  s(
    "ph4",
    "VII.0",
    "Phase 4",
    "Phase 4 — Article 4 lock record",
    "LOCKED — HUMAN ACCEPTED. Compact A.3 unchanged. Phase 5 closed.",
    [
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Constitutional artifact: Article 4 — Authority Is Explicit. Version: v5.3 (no v5.4). Status: LOCKED — HUMAN ACCEPTED. Acceptance: PASS — READY TO LOCK. Compact A.3 unchanged. Articles 1–3 unchanged. ATK-4-01–50 accepted/blocked. INV-4-01–32 accepted. Runtime: SPECIFIED — ENFORCEMENT PENDING. Implementation: NOT CLAIMED COMPLETE. Phase 5 — Article 5: CLOSED / NOT AUTHORIZED.",
      },
      {
        k: "table",
        cols: ["Phase", "Article", "Status"],
        rows: [
          ["Phase 1", "Article 1", "LOCKED / ACCEPTED"],
          ["Phase 2", "Article 2", "LOCKED / ACCEPTED"],
          ["Phase 3", "Article 3", "LOCKED / ACCEPTED"],
          ["Phase 4", "Article 4", "LOCKED / HUMAN ACCEPTED"],
          ["Phase 5", "Article 5", "CLOSED / NOT AUTHORIZED"],
        ],
      },
      {
        k: "callout",
        tone: "note",
        title: "Law milestone ≠ software milestone",
        t: "This lock is constitutional settlement under the amendment process. It is not runtime enforcement complete, not M4/M5, not Day-30 completion, not production or security certification.",
      },
    ],
  ),

  s(
    "a4law",
    "VII",
    "Art. 4 Law",
    "Article 4 — Authority Is Explicit (law)",
    "Explicit, identifiable, bounded, traceable, current, enforceable — or DENY. LOCKED — HUMAN ACCEPTED.",
    [
      {
        k: "callout",
        tone: "note",
        title: "A.3 compact form — not replaced",
        t: "A.3 Article 4 remains the short form. This draft is the deep treatment. Explicit authority is not a human click on every action. LOW/MEDIUM automation remains lawful under Article 1.7 when a valid current chain exists.",
      },
      { k: "h", t: "4.1 Purpose", l: 2 },
      {
        k: "p",
        t: "Article 4 closes authorization by expectation, habit, inference, similarity, urgency, usefulness, prior success, credential possession, provider permission, technical access, role, plan, proposal, policy implication, or model recommendation. None of those alone is valid authority. Authority must be explicit before consequential execution is admitted.",
      },
      { k: "h", t: "4.2 Constitutional rule", l: 2 },
      {
        k: "p",
        t: "Every consequential action requires an identifiable, valid, current authority chain, traceable to a valid Human or constitutional authority source, issued through the Authority System (Article 2), consistent with Articles 1 and 3. Implicit authority is prohibited. Default-allow is prohibited. 'The agent knew what to do' is not an authority source. A missing, malformed, expired, revoked, superseded, ambiguous, out-of-scope, unverifiable, or risk-inconsistent link is not repaired by inference. Result: DEFAULT-DENY at the Trust Kernel; Broker shall not admit.",
      },
      { k: "h", t: "4.3 Explicit authority defined", l: 2 },
      {
        k: "ol",
        items: [
          "Identifiable — known source (Human or constitutional).",
          "Traceable — chain reconstructable to origin.",
          "Scoped — what may be done is defined.",
          "Bound to subject — authorized human/agent/worker identified.",
          "Bound to tenant where applicable.",
          "Bound to product where applicable.",
          "Bound to environment — workspace/staging/production not interchangeable.",
          "Bound to action.",
          "Bound to resource where applicable.",
          "Time-bounded — duration/expiry explicit.",
          "Revocable — mechanism and conditions exist.",
          "Risk-consistent — cannot authorize below the constitutional floor; cannot lower the floor.",
          "Current — expired, revoked, superseded, invalid cannot authorize.",
          "Non-ambiguous — ambiguity is deny.",
        ],
      },
      { k: "h", t: "4.4 Explicit ≠ per-action human click", l: 2 },
      {
        k: "p",
        t: "The constitutional question is whether a valid authority chain exists, not whether a human clicked immediately before execution. LOW may run on a valid current token when the Kernel classifies LOW. MEDIUM may run on governance allow plus token. HIGH/CRITICAL and reserved acts still require Human Authority (Article 1). Standing grants are explicit if they meet 4.3.",
      },
      { k: "h", t: "4.5 Distinctions", l: 2 },
      {
        k: "table",
        cols: ["Concept", "Not"],
        rows: [
          ["Human Authority (Art. 1)", "Origin. Not inferred from text by a model."],
          ["Constitutional authority", "Lawful mechanism under this Constitution."],
          ["Authority Grant", "Bounded record issued by Authority System. Not a role."],
          ["CapabilityToken", "Bounded technical permission of an already-valid grant. Not sovereignty."],
          ["Authentication / credential / role", "Identity or access. Not constitutional authority."],
          ["Technical permission / provider IAM", "Not AGBOFA authority (Art. 2)."],
          ["Policy / Governance decision", "Constrains; not automatically a grant for a specific act."],
          ["AgentProposal / plan", "Not authority (Art. 3)."],
          ["Approval", "Only if issued by authorized Human/constitutional source, bound to proposalId."],
          ["Execution / success / evidence / verification", "Do not retroactively create authority."],
        ],
      },
      { k: "h", t: "4.6 No inferred authority", l: 2 },
      {
        k: "ul",
        items: [
          "The user normally approves this.",
          "This is how we always do it.",
          "The agent has done it before / previous grant probably still applies.",
          "The administrator would obviously agree / similar request.",
          "The policy implies permission.",
          "The environment already has credentials / worker has filesystem access / provider account has permission.",
        ],
      },
      {
        k: "p",
        t: "All insufficient unless the required chain actually exists.",
      },
    ],
  ),

  s(
    "a4chn",
    "VII.C",
    "Art. 4 Chain",
    "Article 4 — chain, scope, delegation, risk, revocation",
    "Missing link = DEFAULT-DENY. SPECIFIED — ENFORCEMENT PENDING.",
    [
      { k: "h", t: "4.7 Authority chain", l: 2 },
      {
        k: "p",
        t: "A chain must answer: source; what granted; to whom; tenant; product; environment; action; resource; risk class; duration; constraints; approval requirement; expired?; revoked?; superseded?; independently verifiable?; auditable? A missing answer is a missing link.",
      },
      { k: "h", t: "4.8 Scope boundaries (no silent cross)", l: 2 },
      {
        k: "ul",
        items: [
          "Tenant A ≠ Tenant B.",
          "Product A ≠ Product B.",
          "Development ≠ production.",
          "Resource A ≠ resource B.",
          "Read ≠ write ≠ delete ≠ deploy ≠ credential operation.",
          "Expired ≠ current.",
          "LOW authority ≠ HIGH/CRITICAL action.",
          "Agent A ≠ Agent B.",
          "Worker execution permission ≠ authority to authorize another action.",
        ],
      },
      { k: "h", t: "4.9 Delegation", l: 2 },
      {
        k: "p",
        t: "Lawful only through the Authority System: authorized source; explicit permission to delegate; identifiably delegator and delegate; scope, duration, constraints; tenant/product/environment and risk preserved; revocable; traceable to origin. No actor delegates more than it possesses. No delegation manufactures Human Authority. No circular agent/worker delegation. No bypass of the Authority System. Technical capability is not sovereignty.",
      },
      { k: "h", t: "4.10 Non-escalation", l: 2 },
      {
        k: "p",
        t: "Authority for one action does not create authority for another. Broader technical capability does not prove constitutional authority outside grant. Authority cannot enlarge through repetition, success, confidence, reputation, history, accumulated permissions, intelligence, consensus, worker privileges, provider permissions, credentials, evidence, or verification. Attempted escalation is rejected.",
      },
      { k: "h", t: "4.11 Risk-class compatibility", l: 2 },
      {
        k: "p",
        t: "Preserve v5.3: LOW documentation/analysis/read-only where classified LOW; MEDIUM code/tests/non-production where classified MEDIUM; HIGH deployments/schema/credentials/cross-tenant; CRITICAL highest controls. Unclassified consequential = HIGH/default-deny. Authority cannot lower the floor. LOW grant cannot authorize HIGH. MEDIUM cannot silently authorize CRITICAL. A token cannot override the floor.",
      },
      { k: "h", t: "4.12 Mechanism roles", l: 2 },
      {
        k: "p",
        t: "Trust Kernel rejects missing/invalid chains. Governance Engine evaluates versioned policy. Authority System issues/delegates/revokes grants. Capability System mints/validates/expires/revokes tokens. Execution Broker admits only a valid chain and token. None is an independent sovereign source of Human Authority.",
      },
      { k: "h", t: "4.13 Emergency", l: 2 },
      {
        k: "p",
        t: "Emergency may freeze, revoke, isolate, contain, preserve evidence, initiate recovery (Article 1). It does not authorize arbitrary deploy, data mutation, amendment, unrestricted grant issuance, tenant takeover, or production execution without required authority. Not a standing source of unrestricted authority.",
      },
      { k: "h", t: "4.14 Revocation", l: 2 },
      {
        k: "p",
        t: "Grants, tokens, delegated authority, and execution eligibility are revocable. Revocation takes precedence over stale cache, provider still-permits, session residue, undeleted token, or prior success. If revoked during execution: halt, destroy worker, preserve evidence, audit. Recovery/freeze semantics preserved.",
      },
      { k: "h", t: "4.15 Failure", l: 2 },
      {
        k: "p",
        t: "If authority cannot be established: DO NOT EXECUTE. Unknown is not probably allowed. Produce rejection, AuditEvent with why and chain-failure class, capability suspension where required, quarantine/freeze/recovery where warranted.",
      },
    ],
  ),

  s(
    "a4adv",
    "VII.A",
    "Art. 4 Attack",
    "Article 4 — adversarial matrix",
    "ATK-4-01–50. BLOCKED / PASS. Compact consequence: reject + audit flag.",
    [
      {
        k: "table",
        cols: ["ID", "Attack", "Bypass", "Enforcement", "Decision"],
        rows: [
          ["ATK-4-01", "Implicit authority", "Expected/useful/urgent", "4.2 4.6", "DENY"],
          ["ATK-4-02", "Agent knew what to do", "Habit/inference", "Compact prohibition", "DENY"],
          ["ATK-4-03", "Default-allow", "Missing link treated as allow", "4.2", "DENY"],
          ["ATK-4-04", "Missing source", "No origin", "Kernel", "DENY"],
          ["ATK-4-05", "Ambiguous source", "Two possible grantors", "4.3.14", "DENY"],
          ["ATK-4-06", "Expired grant", "Use after expiry", "4.3.13", "DENY"],
          ["ATK-4-07", "Revoked grant", "Use after revoke", "4.14", "DENY"],
          ["ATK-4-08", "Wrong tenant", "T1 grant on T2", "4.8 Guard", "DENY"],
          ["ATK-4-09", "Wrong product", "P1 on P2", "4.8", "DENY"],
          ["ATK-4-10", "Wrong environment", "workspace token in production", "4.8", "DENY"],
          ["ATK-4-11", "Wrong resource", "A permitted, B used", "4.8", "DENY"],
          ["ATK-4-12", "Wrong action", "read grant used to deploy", "4.8 4.11", "DENY"],
          ["ATK-4-13", "Wrong subject", "Grant for Agent A used by B", "4.3.4", "DENY"],
          ["ATK-4-14", "Stale approval", "Approval for other proposalId/time", "Art. 1/3", "DENY"],
          ["ATK-4-15", "Cached authorization", "Local cache after revoke", "4.14", "DENY"],
          ["ATK-4-16", "Inherited authorization", "Parent product/tenant assumed", "4.8", "DENY"],
          ["ATK-4-17", "Provider IAM as AGBOFA", "Cloud role as grant", "Art. 2", "DENY"],
          ["ATK-4-18", "Cloud/root as AGBOFA", "Host root as grant", "Art. 1/2", "DENY"],
          ["ATK-4-19", "Credential as authority", "Valid session out of grant", "AuthN ≠ AuthZ", "DENY"],
          ["ATK-4-20", "Role as unlimited", "admin role → all acts", "4.5", "DENY extra"],
          ["ATK-4-21", "Prior success as continuing", "Last deploy succeeded", "4.10", "DENY"],
          ["ATK-4-22", "Similar prior action", "Like last week's change", "4.6", "DENY"],
          ["ATK-4-23", "Policy inference as grant", "Policy 'implies' deploy", "4.5", "DENY"],
          ["ATK-4-24", "Plan as grant", "Plan contains deploy step", "Art. 3", "DENY"],
          ["ATK-4-25", "AgentProposal as grant", "proposalId as Authorization", "Art. 3 4.5", "DENY"],
          ["ATK-4-26", "Token as sovereignty", "Valid token, extra action", "Art. 5; 4.10", "DENY extra"],
          ["ATK-4-27", "Filesystem access as authority", "Worker can write", "4.6", "DENY as grant"],
          ["ATK-4-28", "Environment privilege as authority", "prod kube context", "4.8", "DENY as grant"],
          ["ATK-4-29", "Delegation without authority", "A delegates what A lacks", "4.9", "VOID/DENY"],
          ["ATK-4-30", "Delegation beyond scope", "Widen tenant/env", "4.9", "VOID/DENY"],
          ["ATK-4-31", "Circular delegation", "A↔B", "4.9", "DENY"],
          ["ATK-4-32", "Agent delegation bypass", "A→B outside Authority System", "4.9 Art. 3", "DENY"],
          ["ATK-4-33", "Worker delegation", "Worker grants another", "Worker cannot grant", "DENY"],
          ["ATK-4-34", "Authority escalation", "Repetition/confidence raise", "4.10", "DENY"],
          ["ATK-4-35", "Risk downgrade", "Self-class HIGH→LOW", "Kernel floor", "DENY"],
          ["ATK-4-36", "LOW grant for HIGH act", "Docs grant used to deploy", "4.11", "DENY"],
          ["ATK-4-37", "MEDIUM for CRITICAL", "Non-prod grant on CRITICAL", "4.11", "DENY"],
          ["ATK-4-38", "Unclassified consequential", "Null class", "HIGH then Human/deny", "DENY without HIGH path"],
          ["ATK-4-39", "Emergency bypass", "Emergency mint standing grant", "4.13 Art. 1", "DENY"],
          ["ATK-4-40", "Revoked during execution", "Keep running after revoke", "4.14", "HALT/DENY"],
          ["ATK-4-41", "Token/authority mismatch", "Token action not in grant", "Capability System", "DENY"],
          ["ATK-4-42", "Chain tampering", "Alter grant id in flight", "Audit write-control", "DENY + AUDIT"],
          ["ATK-4-43", "Authority replay", "Reuse grant outside tuple/time", "4.3 current", "DENY"],
          ["ATK-4-44", "Forged human approval", "Fake Approval record", "Art. 1", "DENY"],
          ["ATK-4-45", "AI-generated approval", "Model text as Approval", "Art. 3", "DENY"],
          ["ATK-4-46", "Provider-generated authorization", "Adapter 'allowed'", "Art. 2", "DENY"],
          ["ATK-4-47", "Audit evidence as authority", "Old AuditEvent as grant", "Art. 2/3", "DENY"],
          ["ATK-4-48", "Verification as authority", "Pass ⇒ grant", "Art. 8", "DENY"],
          ["ATK-4-49", "Success as authority", "Deployed ⇒ authorized next", "4.10 Art. 7", "DENY"],
          ["ATK-4-50", "M5/autonomy as escalation", "A5 implies broader grant", "Art. 1/3 4.10", "DENY"],
        ],
      },
    ],
  ),

  s(
    "a4inv",
    "VII.I",
    "Art. 4 Invariants",
    "Article 4 — invariants and failure matrix",
    "INV-4-01–32. Default-deny. SPECIFIED — ENFORCEMENT PENDING.",
    [
      {
        k: "table",
        cols: ["ID", "Invariant", "Test", "Expected"],
        rows: [
          ["INV-4-01", "No consequential action admitted unless its authority chain is explicit, valid, current, in scope, and traceable to a valid Human or constitutional authority source.", "Exec with incomplete chain", "DENY"],
          ["INV-4-02", "Authority source identifiable", "No source field", "DENY"],
          ["INV-4-03", "Chain complete (4.7 questions)", "Any unanswered required link", "DENY"],
          ["INV-4-04", "Chain independently traceable and auditable", "Opaque/unverifiable origin", "DENY"],
          ["INV-4-05", "Subject bound", "Wrong actor uses grant", "DENY"],
          ["INV-4-06", "Tenant bound", "Cross-tenant reuse", "DENY"],
          ["INV-4-07", "Product bound", "Cross-product reuse", "DENY"],
          ["INV-4-08", "Environment bound", "Non-prod grant in prod", "DENY"],
          ["INV-4-09", "Action bound", "Read grant used to deploy", "DENY"],
          ["INV-4-10", "Resource bound", "Wrong resource", "DENY"],
          ["INV-4-11", "Duration/expiry explicit and enforced", "Use after expiry", "DENY"],
          ["INV-4-12", "Revocation enforced and precedes cache", "Cache after revoke", "DENY/HALT"],
          ["INV-4-13", "No inferred authority", "'Always done this way'", "DENY"],
          ["INV-4-14", "Default-deny; no default-allow", "Missing element → allow", "DENY"],
          ["INV-4-15", "No implicit authority", "Expected/urgent/useful", "DENY"],
          ["INV-4-16", "No escalation by success/repetition/confidence", "History raise", "DENY"],
          ["INV-4-17", "No silent cross-boundary reuse", "Any 4.8 cross", "DENY"],
          ["INV-4-18", "Role ≠ unlimited authority", "admin → all acts", "DENY extra"],
          ["INV-4-19", "Credential ≠ authority", "Session without grant", "DENY"],
          ["INV-4-20", "Provider/IAM ≠ AGBOFA authority", "Cloud role as grant", "DENY"],
          ["INV-4-21", "Policy ≠ grant for a specific act", "Implication as grant", "DENY"],
          ["INV-4-22", "Plan ≠ grant", "Plan step execute", "DENY"],
          ["INV-4-23", "Proposal ≠ grant", "proposalId as Authorization", "DENY"],
          ["INV-4-24", "CapabilityToken ≠ sovereignty", "Token extra action", "DENY extra"],
          ["INV-4-25", "Delegation only via Authority System, not beyond possession", "A delegates more than A has", "VOID/DENY"],
          ["INV-4-26", "No circular agent/worker delegation", "A↔B", "DENY"],
          ["INV-4-27", "Risk floor preserved; LOW/MEDIUM cannot authorize HIGH/CRITICAL", "LOW grant deploy", "DENY"],
          ["INV-4-28", "Unclassified consequential = HIGH/deny", "Null class", "HIGH then DENY without HIGH path"],
          ["INV-4-29", "Emergency cannot mint unrestricted/standing grants", "Emergency deploy", "DENY"],
          ["INV-4-30", "Revocation during execution halts admission/worker", "Continue after revoke", "HALT"],
          ["INV-4-31", "Chain integrity: tamper detected → deny + audit", "Altered grant id", "DENY + AUDIT"],
          ["INV-4-32", "Explicit ≠ per-click; valid standing LOW/MEDIUM chain may automate", "Valid LOW token auto-run", "ALLOW only if chain valid"],
        ],
      },
      { k: "h", t: "Failure matrix", l: 2 },
      {
        k: "table",
        cols: ["Failure", "Required response"],
        rows: [
          ["Missing / ambiguous / expired / revoked authority", "DENY"],
          ["Wrong scope / tenant / product / environment / subject", "DENY"],
          ["Invalid delegation", "DENY"],
          ["Risk mismatch / LOW for HIGH / MEDIUM for CRITICAL", "DENY"],
          ["Unclassified consequential action", "HIGH / DENY"],
          ["Forged or AI-generated approval", "DENY"],
          ["Provider-only or credential-only permission", "DENY"],
          ["Stale cached authority", "DENY"],
          ["Authority-chain tampering", "DENY + AUDIT"],
          ["Emergency bypass attempt", "DENY"],
          ["Revocation conflict (cache vs revoke)", "DENY (revoke wins)"],
        ],
      },
    ],
  ),

  s(
    "a4trace",
    "VII.T",
    "Art. 4 Trace",
    "Article 4 — traceability, compatibility, open issues",
    "LOCKED. Compact A.3 unchanged. Phase 5 closed.",
    [
      {
        k: "p",
        t: "Article 4 → P4 (primary; not exclusive) and P1, P3, P5, P13, P14 as applicable (P-set not bijective) → Authority Chain + Authority System + Trust Kernel + Capability System + Broker (+ Isolation Guard on scope) → deterministic rejection of implicit/invalid authority → INV-4-* / ATK-4-* → AuditEvent.why + chain-failure class. No competing grant path.",
      },
      { k: "h", t: "Compatibility", l: 2 },
      {
        k: "table",
        cols: ["Article", "Result", "Constraint (not a draft)"],
        rows: [
          ["1 Human Sovereignty", "PASS", "Origin = Human or constitutional; explicit ≠ every click (1.7)."],
          ["2 AGBOFA Sovereignty", "PASS", "Issuance only via Authority System; IAM/root not grants."],
          ["3 Intelligence ≠ authority", "PASS", "Proposal/plan/AI approval cannot fill a chain link."],
          ["5 Capability scoped", "Constraint", "Token cannot exceed or replace grant; mismatch DENY."],
          ["6 Execution isolated", "Constraint", "Broker admits only valid chain+token; Guard binds scope."],
          ["7 Execution ≠ success", "Constraint", "Success does not retroactively create authority."],
          ["8–9 Verify/evidence", "Constraint", "Neither is a grant."],
          ["10 Audit", "Constraint", "Chain must be auditable; tamper DENY+AUDIT."],
          ["11–13 Agents/autonomy/learning", "Constraint", "No inference, self-delegation, or memory-as-grant."],
          ["16 Provider independence", "Constraint", "Provider permission ≠ AGBOFA authority."],
        ],
      },
      { k: "h", t: "Implementation boundary", l: 2 },
      {
        k: "p",
        t: "Constitutional: no implicit/default-allow; complete current chain. Specified: Kernel reject, Authority System grants, tokens, Broker admit. Implementation: chain schema, expiry/revoke propagation, cache invalidation tests. SPECIFIED ≠ IMPLEMENTED. Not certified, not M4/M5, not Day-30 complete. ENFORCEMENT PENDING.",
      },
      { k: "h", t: "Open issues", l: 2 },
      {
        k: "table",
        cols: ["Issue", "Belongs to"],
        rows: [
          ["Exact grant/chain schema fields in runtime contracts", "Implementation / D.9 — not a law gap"],
          ["Token mint details and oversize checks", "Article 5 deep draft"],
          ["Universal CRITICAL dual-control", "Article 1 potential amendment"],
          ["Federation grant bridging", "Article 2 / future amendment"],
        ],
      },
      {
        k: "callout",
        tone: "law",
        title: "LOCKED — HUMAN ACCEPTED",
        t: "Article 4 is constitutionally settled unless formally amended. Compact A.3 unchanged. Articles 1–3 unchanged. ATK-4-01–50 and INV-4-01–32 accepted. Open issues carried forward (schema → implementation; token oversize → Article 5 unopened; dual-control → Article 1; federation → Article 2). Runtime SPECIFIED — ENFORCEMENT PENDING. Phase 5 CLOSED / NOT AUTHORIZED. Reader ≠ platform.",
      },
    ],
  ),
];
