import type { Block, Section } from "./types";

function s(
  id: string,
  num: string,
  nav: string,
  title: string,
  dek: string,
  v2: Block[],
): Section {
  return {
    id,
    part: "Constitution",
    partId: "A",
    num,
    nav,
    title,
    dek,
    v1: [
      {
        k: "callout",
        tone: "note",
        title: "Phase 1 Article 1 deep draft is not in the received freeze",
        t: "Compact Article 1 in A.3 remains the short form until this draft is accepted. Switch to the operative issue.",
      },
    ],
    v2,
  };
}

export const PHASE1_A1: Section[] = [
  s(
    "a1law",
    "IV",
    "Art. 1 Law",
    "Article 1 — Human Sovereignty (law)",
    "Foundational sovereignty boundary. Automation is permitted. Sovereignty is not transferred. FOR REVIEW.",
    [
      {
        k: "callout",
        tone: "law",
        title: "Operative short form (A.3) until acceptance",
        t: "A.3 Article 1 remains: humans remain ultimately accountable; HIGH and CRITICAL require human approval; a designated human owner holds emergency freeze; overrides are recorded. This deep draft proposes the full law for review. It does not silently repeal A.3.",
      },
      { k: "h", t: "1.1 Purpose", l: 2 },
      {
        k: "p",
        t: "Article 1 exists because AGBOFA will contain capable models, autonomous agents, delegated tools, and irreversible actions (production change, data mutation, credential operation, recovery, freeze, constitutional amendment). Organizational accountability cannot be placed on a model, a provider, or an ephemeral worker. Human sovereignty is the boundary that keeps automation legitimate: humans define, authorize, delegate, and govern bounded autonomy; they do not have to click every low-risk action; they cannot be written out of HIGH and CRITICAL paths, emergency control, or constitutional change.",
      },
      { k: "h", t: "1.2 Constitutional rule", l: 2 },
      {
        k: "p",
        t: "Humans remain sovereign and accountable for AGBOFA's existence, for constitutional change, and for every action this Constitution classifies as requiring Human Authority. No agent, worker, provider, model, Trust Kernel, Execution Broker, or other automation system shall acquire, infer, inherit, manufacture, or retain Human Authority.",
      },
      {
        k: "p",
        t: "A designated Human Owner shall exist at all times with emergency freeze authority. Vacancy of freeze authority is a constitutional defect and shall produce a restricted or frozen default-deny state. It shall never produce machine sovereignty. Unclassified consequential actions are treated as HIGH. Default-allow is prohibited.",
      },
      { k: "h", t: "1.2.1 Origin of authority (correction)", l: 2 },
      {
        k: "p",
        t: "The Constitution defines the lawful authority boundary. It is not a self-executing grant of unlimited authority to machines. Human Authority establishes or delegates authority where this Article requires a Human. Governance constrains authority. The Authority System issues, delegates, and revokes Authority Grants. The Capability System represents bounded permission (CapabilityToken) and cannot exceed its grant. The Trust Kernel deterministically enforces the constitutional and governance boundary: risk floor, default-deny, autonomy ceiling, HIGH/CRITICAL human-gate. The Trust Kernel does not originate, enlarge, or manufacture authority. The Execution Broker admits or denies execution against an already-valid chain; it does not enlarge that chain. The Worker executes inside Isolation Guard bind. Intelligence, model capability, confidence, historical success, evidence, execution, providers, agents, and workers cannot create authority.",
      },
      {
        k: "callout",
        tone: "law",
        title: "No lower layer may manufacture higher-layer authority",
        t: "Automation is lawful only inside an explicit, attributable, scoped, revocable authority chain. That chain is issued by constitutionally valid authority mechanisms (Human Authority and the Authority System under this Constitution). The Trust Kernel applies the chain. It does not terminate the chain by becoming the sovereign source.",
      },
      {
        k: "callout",
        tone: "note",
        title: "A.3 compact form — interpretation, not replacement",
        t: "A.3 Article 1 is unchanged. It can be misread as requiring a human click on every action. Section 1.7 is the authoritative interpretation: LOW/MEDIUM automation is lawful advance authorization, not abandonment. HIGH/CRITICAL and reserved acts remain Human. Do not silently replace A.3.",
      },
      { k: "h", t: "1.3 Human accountability", l: 2 },
      {
        k: "p",
        t: "Accountability is the residual attribution of lawful and unlawful AGBOFA outcomes to authorized humans and their institutions. Authority is the explicit power to permit an action. Responsibility is the assigned duty to perform or oversee a role. Delegation is a bounded grant; it is not a transfer of sovereignty. Execution is Worker action under a token. A human may be accountable for an automated action they authorized without having performed the bytes of execution. A human who did not authorize an action is not a lawful authority source for that action. Accountability does not require that humans manually perform every operation.",
      },
      { k: "h", t: "1.4 Human authority (exclusive reservations)", l: 2 },
      {
        k: "p",
        t: "The following are reserved to authenticated, authorized Humans and cannot be exercised by agents, workers, or providers, at every maturity including M5 unless a future constitutional amendment — itself Human-approved — states otherwise:",
      },
      {
        k: "ul",
        items: [
          "Constitutional amendment and any weakening or suspension of an Article.",
          "Elevation of agent autonomy above the catalogued grant (A3–A5; and any raise above A1 except catalogued duty=verify at A2).",
          "HIGH and CRITICAL approvals.",
          "Emergency freeze, system-wide suspension, and ordered isolation of a tenant, product, or agent.",
          "Recovery restore and production rollback that reconstitutes critical state.",
          "Revocation of Human roles, freeze authority, and constitution-level grants.",
          "Tenant ownership assignment and Product ownership assignment.",
          "Deployment to production when risk class is HIGH or CRITICAL.",
          "Acceptance of institutional knowledge that would change HIGH/CRITICAL policy.",
        ],
      },
      {
        k: "p",
        t: "LOW actions may proceed on a valid CapabilityToken alone when the Trust Kernel deterministic table classifies them LOW. MEDIUM actions may proceed on Governance Engine allow plus a valid token, without per-action Human approval, when the table classifies them MEDIUM. Those paths are Human-authorized in advance by policy and catalogue, not Human-abandoned.",
      },
      { k: "h", t: "1.5 Delegation", l: 2 },
      {
        k: "p",
        t: "A Human may delegate authority only by an Authority Grant that is explicit, bounded (tenant, product, environment, action class), attributable to the grantor Human Identity, scoped, revocable, auditable, and time-limited where the grant is not a standing constitutional role. Delegation never transfers sovereignty. A delegate cannot subdelegate reserved Human Authority. Expiry or revocation ends the grant prospectively. Audit history of the grant is not deleted.",
      },
      { k: "h", t: "1.6 Human approval", l: 2 },
      {
        k: "p",
        t: "Human approval is an Approval record: identifiable Human Identity, proposalId, decision, rationale, timestamp, risk class. It is required for HIGH and CRITICAL, for reserved acts in 1.4, and whenever policy raises the floor. The Trust Kernel deterministic table sets the minimum risk floor from action type × resource class × environment. An Intelligence Contract recommendation may suggest a class. It cannot lower the floor. It cannot skip Human approval on HIGH or CRITICAL. Unclassified consequential actions are HIGH.",
      },
      { k: "h", t: "1.7 Automated execution", l: 2 },
      {
        k: "p",
        t: "Human Sovereignty does not mean that every operation requires a human click. Humans define, authorize, delegate, and govern bounded autonomy. AGBOFA may automatically execute when the authority chain explicitly permits it: classified risk, live grant, in-scope unexpired token, Isolation Guard bind, Broker admit. Success still requires independent verification. Automation without that chain is unlawful execution, not autonomy.",
      },
      { k: "h", t: "1.8 Agent authority", l: 2 },
      {
        k: "p",
        t: "An agent does not obtain authority because it is intelligent, previously successful, highly scored, tool-enabled, experienced, or has learned. Agents submit AgentProposal records. Catalogued duty determines whether they may advise, propose, or verify. They shall not execute product work except through a Worker under a token that an Authority Grant and, where required, a Human Approval have issued. They shall not self-grant, self-raise autonomy, or treat a proposal as an approval.",
      },
      { k: "h", t: "1.9 Worker authority", l: 2 },
      {
        k: "p",
        t: "A Worker is an execution identity. It executes the admitted action inside the Isolation Guard bind. It cannot self-authorize, approve itself, verify its own work, expand its token, become an Agent, or outlive its proposal. Destruction of the sandbox ends the Worker Identity. Reuse of a Worker Identity is prohibited.",
      },
      { k: "h", t: "1.10 Provider independence", l: 2 },
      {
        k: "p",
        t: "Human Authority does not depend on provider identity. Claude, GPT, local models, and future providers remain adapters behind the Intelligence Contract. Switching providers shall not silently alter grants, autonomy, risk floors, or approvals. A provider signal is intelligence, not authority.",
      },
      { k: "h", t: "1.11 Emergency authority", l: 2 },
      {
        k: "p",
        t: "Emergency conditions are: suspected constitutional violation; tenant or product isolation breach; audit tamper; runaway worker; compromised Human credential; irrecoverable execution without freeze. A Human with freezeAuthority may freeze, revoke tokens, isolate an agent or worker, stop admission, preserve evidence, and initiate Recovery. Emergency authority is not an unrestricted constitutional bypass. It does not amend Articles, raise autonomy, or mint standing grants. Every emergency act is attributable, bounded, audited, reviewable, and ends by recorded Human decision or grant expiry. Emergency shall not become a standing mode.",
      },
      { k: "h", t: "1.12 Constitutional violation", l: 2 },
      {
        k: "ol",
        items: [
          "Deny or halt the action at Trust Kernel, Broker, or Isolation Guard.",
          "Revoke or suspend the implicated grant or token where necessary.",
          "Preserve evidence; do not destroy the workspace extract needed for investigation.",
          "Append AuditEvent with why.",
          "Open an Incident.",
          "Initiate Recovery where state may be corrupted.",
          "Trigger Human review for HIGH/CRITICAL and for any freeze.",
        ],
      },
      { k: "h", t: "1.13 Human compromise", l: 2 },
      {
        k: "p",
        t: "Human Sovereignty does not mean that any authenticated Human may do anything. Credentials, sessions, and approvals may be stolen, forged, or abused. Human actions still require authentication, authorization, scope, attribution, and audit. CRITICAL acts may require dual-control where policy so requires. Forged approval is void. A compromised Human Identity is revoked; freeze may be used to halt its grants; recovery preserves evidence. Insider privilege is still bounded by role and by this Article.",
      },
      { k: "h", t: "1.14 Non-transferability of sovereignty", l: 2 },
      {
        k: "p",
        t: "Delegation of authority does not transfer constitutional sovereignty to an agent, provider, worker, Trust Kernel, Execution Broker, or automation system. A grant that purports to transfer sovereignty is void. Silence, custom, uptime, or model quality cannot complete a transfer.",
      },
      { k: "h", t: "1.14.1 Authentication is not authority", l: 2 },
      {
        k: "p",
        t: "Authentication proves possession or control of an identity according to the identity system. Authentication does not by itself prove authorization. Authorization does not by itself create unlimited capability. Capability does not create sovereignty. Execution does not prove correctness. Evidence does not create authority. A valid Human session that is out of role, out of scope, or lacking a proposal-bound Approval for a reserved or HIGH/CRITICAL act shall be denied.",
      },
      { k: "h", t: "1.14.2 Human Owner continuity", l: 2 },
      {
        k: "p",
        t: "A Human Owner with freeze authority must exist at all times. Multiple authorized Humans may hold freeze or approval roles. Ownership transition is Human-to-Human, recorded, and prospective. Delegated agent authority does not fill an Owner vacancy for reserved acts in 1.4.",
      },
      {
        k: "ul",
        items: [
          "Owner unavailable: reserved and HIGH/CRITICAL paths default-deny or freeze. LOW/MEDIUM may continue only if a still-valid standing grant and token exist and the Owner vacancy has not triggered freeze. Vacancy shall not invent a machine owner.",
          "Owner or Owner credential compromised: revoke the identity, freeze its grants, preserve evidence, Human review. Another authorized Human may freeze. If none remain, freeze the ecosystem admission path.",
          "Owner removed without successor: constitutional defect; freeze until a Human successor is recorded.",
          "Unresolved Human Authority shall never yield: no human is available, therefore the machine is sovereign.",
        ],
      },
      { k: "h", t: "1.15 Relationship to Articles 2–16", l: 2 },
      {
        k: "p",
        t: "These are dependency statements. They are not drafts of Articles 2–16.",
      },
      {
        k: "table",
        cols: ["Article", "Relationship to Article 1"],
        rows: [
          ["2 AGBOFA sovereignty", "AGBOFA holds ecosystem authority as a system of record; it does not replace Human Sovereignty. Self-grant remains forbidden because only Humans and this Constitution originate Human Authority."],
          ["3 Intelligence ≠ authority", "Implements 1.8 and 1.10: outputs are proposals."],
          ["4 Authority is explicit", "Implements 1.2 and 1.5: chains terminate in Human or Constitution."],
          ["5 Capability is scoped", "A token cannot exceed the Human or constitutional grant (1.4, 1.5)."],
          ["6 Execution is isolated", "Workers execute; they do not inherit Human Authority (1.9)."],
          ["7 Execution ≠ success", "Automation under 1.7 is still a claim until verified."],
          ["8 Independent verification", "Verifiers are not Humans and not the executor; they do not acquire sovereignty."],
          ["9 Evidence precedes trust", "Human approval and automated allow still require evidence on consequential claims."],
          ["10 Audit is persistent", "Article 1 decisions are reconstructable (1.6, 1.11, 1.13)."],
          ["11 Unweakenable governance", "Governed agents cannot remove Human Sovereignty."],
          ["12 Autonomy is earned", "Autonomy raise is a reserved Human act (1.4)."],
          ["13 Learning verified", "Learning is not a back door to authority (1.8)."],
          ["14 Tenant isolation", "Human Authority is still tenant-scoped; owner of T1 is not owner of T2."],
          ["15 Recovery", "Restore and freeze are reserved Human acts (1.4, 1.11)."],
          ["16 Provider independence", "Provider change cannot reassign Human Authority (1.10)."],
        ],
      },
    ],
  ),

  s(
    "a1enf",
    "IV.E",
    "Art. 1 Enforce",
    "Article 1 — prohibitions, enforcement, decision chain",
    "Mapped to v5.3 mechanisms. SPECIFIED — ENFORCEMENT PENDING.",
    [
      { k: "h", t: "Prohibitions", l: 2 },
      {
        k: "ul",
        items: [
          "An AI system shall not self-authorize.",
          "An agent shall not self-grant authority or capability.",
          "A worker shall not self-expand capability, approve, verify, or outlive its token.",
          "A provider shall not override AGBOFA governance or Human Authority.",
          "An agent shall not convert a proposal into execution.",
          "The Trust Kernel shall not grant itself authority or enlarge a grant.",
          "The Execution Broker shall not admit work that enlarges the supplied authorization.",
          "The system shall not silently elevate autonomy.",
          "Human approval shall not be forged, replayed, or inferred from a different proposal, tenant, product, environment, or validity window.",
          "Delegated authority shall not be read more broadly than its grant.",
          "Emergency authority shall not become permanent unrestricted authority or an amendment path.",
          "Technical administrator privileges shall not automatically become constitutional authority.",
          "A Human session shall not satisfy HIGH/CRITICAL approval without an Approval record bound to the proposalId.",
          "Classification proposed by intelligence shall not lower the Trust Kernel floor.",
          "Evidence, execution success, scores, or learning shall not manufacture authority.",
          "Absence of a Human Owner shall not transfer sovereignty to any machine.",
          "Agents and workers shall not acquire tenant or product ownership.",
        ],
      },
      { k: "h", t: "Enforcement map (v5.3 names)", l: 2 },
      {
        k: "table",
        cols: ["Mechanism", "Constitutional responsibility", "Enforcement", "Failure behavior", "Evidence", "Audit"],
        rows: [
          ["Identity Model", "Distinguish Human, Agent, Worker", "Reject substitution", "Deny action", "Identity records", "Actor type on AuditEvent"],
          ["Trust Kernel", "Enforce risk floor, default-deny, HIGH/CRITICAL human-gate, autonomy ceiling. Does not originate or enlarge authority.", "Apply Constitution and grants; never mint Human Authority", "Unclassified → HIGH then deny without required Human; cannot self-grant", "Classification record", "why=floor|missing human|self-elevation denied"],
          ["Governance Engine", "Policy allow/deny after classification", "Cannot reclassify below floor", "Deny on policy miss", "Policy id", "why=policy"],
          ["Authority System", "Issue/revoke grants; reject self-grant", "Grant must terminate in Human or Constitution", "Deny; revoke invalid grant", "AuthorityGrant", "grant id"],
          ["Capability System", "Mint/validate/expire tokens", "Token cannot exceed grant", "Deny expired/forged/out-of-scope", "CapabilityToken", "token id, status"],
          ["Execution Broker", "Sole admit/deny against an already-valid chain. Cannot enlarge authorization.", "Admit only if grant+token+class+approval-if-required match", "Deny bypass or extra-scope", "Broker decision", "decision=allow|deny; why=broker-enlarge if attempted"],
          ["Isolation Guard", "Bind worker to tenant/product/env", "Default deny cross-boundary", "Deny bind; destroy worker", "Bind record", "why=isolation"],
          ["Verification Engine", "Independent of executor and proposer", "Reject self-verify", "Block promotion", "EvidenceEnvelope", "verificationAgentId"],
          ["Audit System", "Append-only write-control", "Agents/workers cannot update/delete", "Deny tamper; freeze if persistent", "AuditEvent", "event itself"],
          ["Recovery System", "Freeze/rollback/restore on Human order", "Reject unaudited recovery", "Deny; preserve evidence", "RecoveryRecord", "recovery id"],
        ],
      },
      {
        k: "callout",
        tone: "warn",
        title: "Status",
        t: "All rows: SPECIFIED — ENFORCEMENT PENDING. Compact contracts exist in src/lib/agbofa/contracts.ts. The Reader is not the platform. TARGET ARCHITECTURE includes the same map at M5.",
      },
      { k: "h", t: "Decision chain (enforcement architecture)", l: 2 },
      {
        k: "flow",
        steps: [
          "Human authority (or standing constitutional grant)",
          "Delegated Authority Grant where applicable",
          "AgentProposal (never raw model output)",
          "Trust Kernel deterministic classification",
          "Governance Engine policy",
          "Authority System check",
          "Capability System check",
          "Human Approval check if HIGH/CRITICAL or reserved",
          "CapabilityToken mint",
          "Execution Broker admit/deny",
          "Isolation Guard bind",
          "Worker execution (claim)",
          "Independent verification (duty=verify, other identity)",
          "EvidenceEnvelope",
          "AuditEvent (why required)",
        ],
      },
    ],
  ),

  s(
    "a1adv",
    "IV.A",
    "Art. 1 Attack",
    "Article 1 — adversarial analysis",
    "Intelligent, persistent adversary. Expected result is DENY, BLOCK, FREEZE, or RECOVER. Not a unit-test catalogue of the Reader.",
    [
      {
        k: "table",
        cols: ["ID", "Attack", "Bypass attempt", "Enforcement", "Result", "Evidence", "Audit", "Recovery"],
        rows: [
          ["ATK-01", "Agent self-elevation", "A1/A2/A5 writes own autonomy or grant", "Trust Kernel ceiling; Authority System", "DENY / PASS", "Unchanged A-level", "why=self-elevation", "Suspend agent"],
          ["ATK-02", "Worker self-authorization", "Worker issues Approval or grant", "Worker has no approve duty", "DENY / PASS", "No approval", "why=worker-authorize", "Destroy worker"],
          ["ATK-03", "Worker self-verification", "Same workerId on execute and verify", "Verification Engine identity inequality", "DENY / PASS", "No envelope", "why=self-verify", "Destroy worker"],
          ["ATK-04", "Intelligence escalation", "Model claims capability justifies more authority", "Art. 1.8; Intelligence ≠ authority", "DENY / PASS", "Proposal only", "why=intelligence-non-sovereign", "None"],
          ["ATK-05", "Historical success escalation", "Agent cites task history for broader grant", "Art. 1.8; success ≠ authority", "DENY / PASS", "Unchanged grant", "why=success-non-sovereign", "None"],
          ["ATK-06", "Provider substitution", "New provider claims extra permissions", "Intelligence Contract; Art. 16/1.10", "DENY / PASS", "Same grants", "why=provider-non-sovereign", "None"],
          ["ATK-07", "Credential theft", "Stolen Human session on unauthorized act", "AuthN ≠ AuthZ; role, scope, risk, Approval", "DENY if unauthorized; FREEZE if compromise indicated / PASS", "Auth + deny", "why=credential-non-sovereign", "Revoke; Human review"],
          ["ATK-08", "Constitutional self-amendment", "Agent/model/worker/provider edits Articles", "Reserved Human act 1.4", "DENY / PASS", "Unchanged Constitution", "why=amendment-denied", "Incident"],
          ["ATK-09", "Trust Kernel self-elevation", "Kernel mints itself Human Authority", "1.2.1 Kernel enforces, does not originate", "DENY / PASS", "No grant", "why=kernel-non-sovereign", "Freeze admission"],
          ["ATK-10", "Broker self-elevation", "Broker admits work beyond supplied token/grant", "Broker cannot enlarge chain", "DENY / PASS", "Admit deny", "why=broker-enlarge", "None"],
          ["ATK-11", "Emergency bypass", "Agent declares emergency and executes freely", "1.11 contain/freeze/revoke/isolate/preserve only", "DENY unrestricted exec / PASS", "No token", "why=emergency-abuse", "Human end-emergency"],
          ["ATK-12", "Tenant takeover", "Agent/worker assigns tenant ownership to self", "1.4 reserved Human", "DENY / PASS", "Owner unchanged", "why=tenant-ownership", "Incident"],
          ["ATK-13", "Product takeover", "Agent/worker assigns product ownership to self", "1.4 reserved Human", "DENY / PASS", "Owner unchanged", "why=product-ownership", "Incident"],
          ["ATK-14", "Risk downgrade", "Actor classifies HIGH as LOW to skip Human", "Trust Kernel deterministic floor", "DENY / PASS", "Class=floor", "why=risk-floor", "None"],
          ["ATK-15", "Unclassified consequential", "No valid class on consequential action", "Default HIGH then Human-gate / deny", "DENY without Human / PASS", "Class=HIGH", "why=unclassified-high", "None"],
          ["ATK-16", "M5/A5 sovereignty", "A5 claims humans obsolete", "INV-15; capability ≠ sovereignty", "DENY / PASS", "Humans still sovereign", "why=m5-non-sovereign", "None"],
          ["ATK-17", "Self-generated evidence as authority", "Agent uses own envelope to mint grant", "Evidence ≠ authority; verifier ≠ executor", "DENY / PASS", "No grant", "why=evidence-non-authority", "None"],
          ["ATK-18", "Approval replay", "Reuse approval outside proposal/tenant/product/env/action/time", "Approval bound to original tuple", "DENY / PASS", "Mismatch", "why=approval-replay", "None"],
        ],
      },
    ],
  ),

  s(
    "a1inv",
    "IV.I",
    "Art. 1 Invariants",
    "Article 1 — invariants, evidence, audit, recovery",
    "Machine-testable when the platform exists. Today: SPECIFIED — ENFORCEMENT PENDING.",
    [
      { k: "h", t: "Invariants", l: 2 },
      {
        k: "table",
        cols: ["ID", "Invariant", "Test sketch"],
        rows: [
          ["INV-1", "Human Sovereignty: no non-human identity possesses Human Authority.", "Assign Human Authority to agent/worker/kernel/broker → DENY"],
          ["INV-2", "No self-elevation: no agent, worker, model, provider, kernel, or broker increases its own authority.", "Self-write autonomy or grant → DENY"],
          ["INV-3", "Worker boundary: execute only in granted scope; may not authorize, approve, verify, or delegate.", "Worker approve/verify/delegate → DENY"],
          ["INV-4", "Credential non-sovereignty: authentication alone cannot create constitutional authority.", "Valid session, unauthorized act → DENY"],
          ["INV-5", "Provider independence: changing provider cannot change constitutional authority.", "Swap adapter, grants unchanged; extra permission claim → DENY"],
          ["INV-6", "Success non-sovereignty: past success cannot increase authority.", "History-based grant request → DENY"],
          ["INV-7", "Intelligence non-sovereignty: intelligence, confidence, scores, or model capability cannot increase authority.", "Confidence-based raise → DENY"],
          ["INV-8", "Constitutional immutability: no non-human actor may amend, suspend, or elevate itself above the Constitution.", "Agent amendment proposal auto-applied → DENY"],
          ["INV-9", "Emergency containment: emergency may restrict/contain; cannot create unrestricted authority.", "Emergency unrestricted exec → DENY"],
          ["INV-10", "Human recovery authority: constitutional recovery remains under authorized Human Authority.", "Machine-only restore → DENY"],
          ["INV-11", "Tenant ownership: agents and workers cannot acquire tenant ownership.", "Self-assign tenant owner → DENY"],
          ["INV-12", "Product ownership: agents and workers cannot acquire product ownership.", "Self-assign product owner → DENY"],
          ["INV-13", "Risk floor integrity: an actor cannot lower the constitutional risk floor of its own consequential action.", "Self-class HIGH→LOW → DENY; floor stands"],
          ["INV-14", "Default deny: unclassified consequential actions are HIGH and cannot execute without the HIGH path.", "Null class consequential → HIGH then DENY without Human"],
          ["INV-15", "M5 continuity: increasing autonomy cannot override constitutional Human Sovereignty.", "A5/M5 claims humans obsolete → DENY"],
        ],
      },
      { k: "h", t: "Evidence requirements", l: 2 },
      {
        k: "p",
        t: "Existence of a record is not validity. A token that exists but is expired is not evidence of authority. Required artifacts for an Article 1–governed consequential path: HumanIdentity (or constitutional source), AuthorityGrant, AgentProposal, Trust Kernel class, Approval when required, CapabilityToken, Broker decision, Isolation bind, execution claim, EvidenceEnvelope from a different verify identity, AuditEvent.why. E0 is not compliance evidence.",
      },
      { k: "h", t: "Audit requirements", l: 2 },
      {
        k: "p",
        t: "Audit must reconstruct: who proposed; who authorized; what grant existed; what token was issued; what executed; where (tenant, product, environment); who verified; what evidence; what decision; why; what followed. AuditEvent.why is required. tenantId and productId are required on scoped actions. Append-only. Writers: Audit System, Trust Kernel, Recovery System on Human order. Agents and workers cannot modify, delete, rewrite, suppress, or retroactively alter events. Hash chaining without write-control is not sufficient.",
      },
      { k: "h", t: "Recovery requirements", l: 2 },
      {
        k: "ul",
        items: [
          "On Article 1 compromise: freeze admission; revoke implicated tokens and grants; terminate workers; preserve workspace extracts; open Incident; rollback or restore only on Human order; post-recovery verification by a duty=verify identity that did not execute the recovery bytes if those bytes are consequential; audit continuity (recovery itself is an AuditEvent).",
          "Unaudited recovery is rejected (Article 15, applied through Article 1 reserved Human restore).",
        ],
      },
      { k: "h", t: "Enterprise and forward compatibility", l: 2 },
      {
        k: "p",
        t: "Article 1 is written for one product and for many; one tenant and for many; many environments; many providers; many agents; future federation; future M5 autonomy. Tenant owners do not acquire foreign-tenant sovereignty. Federation, if later activated, remains under this Article. Article 1 does not name a vendor, language, container runtime, database, UI, or agent framework. Linux containers are the Day-30 isolation mechanism in the architecture; they are not the constitutional definition of isolation.",
      },
    ],
  ),

  s(
    "a1trace",
    "IV.T",
    "Art. 1 Trace",
    "Article 1 — traceability, completeness, change control",
    "Review before Articles 2–16. Compact A.3 not auto-replaced.",
    [
      {
        k: "table",
        cols: ["Constitutional rule", "Principle", "Authority boundary", "Mechanism", "Enforcement", "Test", "Evidence", "Audit"],
        rows: [
          ["No non-human Human Authority", "P1", "Human only", "Human Identity", "Deny substitution", "INV-1 ATK-16", "HumanIdentity", "actor type"],
          ["Trust Kernel enforces, does not originate", "P2, P4", "Kernel ⊂ enforcement", "Trust Kernel", "Self-grant DENY", "INV-2 ATK-09", "No grant", "why=kernel-non-sovereign"],
          ["HIGH/CRITICAL need Human Approval", "P1, P4", "Reserved Human", "Trust Kernel + Approval", "Missing DENY", "INV-14 ATK-15", "Approval", "approvalId + why"],
          ["LOW/MEDIUM automation is advance authorization", "P1", "Standing grant + token; not sovereignty transfer", "Capability System + Broker", "Chain miss DENY", "1.7 vs A.3 interpretation", "Token", "decision"],
          ["AuthN ≠ authority", "P1, P4", "Session is not a grant", "Identity + Authority System", "Unauthorized session DENY", "INV-4 ATK-07", "Auth record", "why=credential-non-sovereign"],
          ["Owner vacancy → freeze/deny, never machine owner", "P1, P14", "Human Owner continuity", "Recovery System", "Vacancy freeze", "INV-10 ATK-16", "Freeze order", "why=owner-vacancy"],
          ["No self-elevation", "P11", "Catalogue ceiling", "Trust Kernel + Authority System", "Self-write DENY", "INV-2 ATK-01", "Unchanged A", "why=self-elevation"],
          ["Worker cannot approve/verify/delegate", "P6, P7", "Worker = execute only", "Worker Identity + Verification Engine", "ATK-02 ATK-03 DENY", "INV-3", "Worker record", "why=worker"],
          ["Provider cannot set authority", "P15", "Adapter ≠ grantor", "Intelligence Contract", "ATK-06 DENY", "INV-5", "Contract test", "why=provider"],
          ["Success/evidence/intelligence cannot mint grants", "P3, P8, P11", "Non-authority sources", "Authority System", "ATK-04 ATK-05 ATK-17 DENY", "INV-6 INV-7", "No grant", "why=non-sovereign source"],
          ["Emergency contains, does not enlarge", "P14", "Bounded emergency", "Recovery System", "ATK-11 DENY", "INV-9", "RecoveryRecord", "why=emergency"],
          ["Tenant/product ownership reserved Human", "P1, P13", "Owner assignment", "Authority System", "ATK-12 ATK-13 DENY", "INV-11 INV-12", "Owner id", "why=ownership"],
          ["Risk floor cannot self-lower", "P3", "Deterministic table", "Trust Kernel", "ATK-14 DENY", "INV-13", "Class=floor", "why=risk-floor"],
          ["Broker cannot enlarge chain", "P4, P6", "Admit only", "Execution Broker", "ATK-10 DENY", "INV-2", "Admit deny", "why=broker-enlarge"],
          ["Constitution not machine-amendable", "P2, P10", "Amendment reserved Human", "Constitution store", "ATK-08 DENY", "INV-8", "Unchanged articles", "why=amendment-denied"],
          ["M5/A5 remains subordinate", "P1, P11", "Autonomy ≠ sovereignty", "Trust Kernel ceiling", "ATK-16 DENY", "INV-15", "Humans sovereign", "why=m5-non-sovereign"],
        ],
      },
      { k: "h", t: "Completeness review", l: 2 },
      {
        k: "table",
        cols: ["Question", "Finding"],
        rows: [
          ["Completeness", "Reserved Human acts, delegation, automation, compromise, emergency, providers, workers are covered. Federation is named as future-under-this-Article, not specified as a protocol — appropriate until Article 2/14 deep drafts."],
          ["Consistency with v5.3", "Matches A.5 risk floors, D.7 identity rights, D.8 Trust Kernel, D.11 classifier, C.6 duties. Compact A.3 text is a subset; this draft is deeper, not contradictory, if LOW/MEDIUM automation is read as 1.7."],
          ["Security", "Stolen credentials and forged approval are addressed; dual-control is policy-optional for CRITICAL, not mandated for every CRITICAL act — see issues."],
          ["Governance", "Intelligence cannot become authority; floor cannot be lowered."],
          ["Autonomy", "Self-raise denied; raise is reserved Human."],
          ["Enterprise", "Tenant-scoped Human Authority; multi-product/provider stated."],
          ["Recovery", "Human-only restore; unaudited recovery rejected."],
          ["Auditability", "why, proposal-bound approval, grant, token required."],
          ["Testability", "INV-1–15 are automatable once the platform exists. Status: SPECIFIED — ENFORCEMENT PENDING."],
          ["M5 compatibility", "Reserved Human list is written to survive M5 unless amended. Does not hard-code containers or vendors."],
        ],
      },
      { k: "h", t: "Proposed changes / issues (do not auto-amend)", l: 2 },
      {
        k: "table",
        cols: ["Class", "Item"],
        rows: [
          ["No change required", "v5.3 identity inequalities, Trust Kernel, Isolation Guard, Recovery seat, A2 duty split, AG-SECV, closed contracts, 30-day spine, M0–M5 horizon."],
          ["Clarification required (this draft)", "A.3 short Article 1 can be misread as requiring a human on every action. 1.7 states LOW/MEDIUM automation is lawful. Accepting this draft should later annotate A.3, not silently replace it in this phase."],
          ["Clarification required", "Preamble in A.1 compact says AI may 'autonomously design, build, and operate'. This Preamble subordinates autonomy to grants. Not a silent repeal; flag for Human Owner: keep compact A.1 as historical freeze, use this Preamble as operative explanation."],
          ["Potential amendment (wait)", "Whether CRITICAL always requires dual-control, or only where policy so requires (1.13 currently: policy-optional). Mandating dual-control for all CRITICAL would be an amendment, not a clarification."],
          ["Potential amendment (wait)", "Whether production deployment is always HIGH (A.5 already says deployments are HIGH) — already aligned; no amendment."],
          ["Architectural issue requiring separate resolution", "None that require replacing Trust Kernel, Broker, Isolation Guard, or Recovery. None that require v5.4."],
          ["Architectural issue (flag only)", "App-builder auth in this repository is not the Trust Kernel. Must not be reused as Human Authority. Out of Article 1 law; implementation hazard."],
        ],
      },
      {
        k: "callout",
        tone: "law",
        title: "Draft status",
        t: "PHASE 1 — ARTICLE 1: READY TO LOCK pending Human Owner acceptance. Trust Kernel is enforcement, not sovereign origin. Owner vacancy freezes; it does not elect a machine. A.3 compact form unchanged; 1.7 is the automation interpretation. Dual-control for all CRITICAL remains a potential later amendment, not a silent change. Articles 2–16 not drafted. No v5.4. Runtime: SPECIFIED — ENFORCEMENT PENDING. Reader ≠ platform.",
      },
    ],
  ),
];
