export const TRACKS = [
  { id: "k", name: "Kernel", crew: "Trust, authority, capability, identity" },
  { id: "i", name: "Intelligence", crew: "Contract, adapters, A0–A2 runtime" },
  { id: "p", name: "Factory", crew: "Discovery through plan, two products" },
  { id: "x", name: "Execution", crew: "Broker, workspace, workers, deploy" },
  { id: "g", name: "Guard", crew: "Verify, evidence, audit, isolation, ops" },
] as const;

export type TrackId = (typeof TRACKS)[number]["id"];

export type StrikeDay = {
  d: number;
  wave: "W1" | "W2" | "W3" | "W4";
  gate?: string;
  focus: string;
  k: string;
  i: string;
  p: string;
  x: string;
  g: string;
};

export const WAVES = [
  {
    id: "W1",
    name: "Kernel live",
    days: "1–7",
    certify: "M0 certified internally; M1 skeleton",
    cells: {
      k: ["Encode 16 articles as invariants", "Domain + identity", "Authority chains", "Capability tokens", "Gate 1 + Gate 2"],
      i: ["Intelligence Contract interface", "Claude adapter stub", "Local adapter seam", "Context packet v1"],
      p: ["Passport schema + lifecycle union", "Discovery intake", "Requirements skeleton", "Blueprint skeleton"],
      x: ["Workspace contract", "Worker contract", "Broker health", "Tenant id on every workspace"],
      g: ["Audit schema + hash chain", "Evidence envelope", "Policy on every request", "Isolation Guard interface"],
    },
  },
  {
    id: "W2",
    name: "Factory live",
    days: "8–14",
    certify: "M2 path proven — idea to governed spec",
    cells: {
      k: ["Risk class on every proposal", "Human Owner approval path", "Gate 3"],
      i: ["A0 advisory runtime", "A1 proposal catalogue", "Architect Agent", "Second provider returns a real completion"],
      p: ["Discovery live", "Requirements + Passport write", "Blueprint + architecture + plan", "Product 1 approved spec"],
      x: ["Proposal bus", "Plan is not a deploy"],
      g: ["Rate limit skeleton", "Evidence of each proposal", "Gate 4 + Gate 5"],
    },
  },
  {
    id: "W3",
    name: "Execute and prove",
    days: "15–21",
    certify: "M1 complete — execute, verify, deploy Product 1",
    cells: {
      k: ["Tokens on every execution"],
      i: ["Verification Agent A2", "No agent executes directly"],
      p: ["Product 1 implementation under passport", "Product 2 factory start"],
      x: ["Isolated workspace + worker", "Build + deploy + environments", "Post-deploy verify"],
      g: ["Independent verification", "Evidence hashing", "Append-only audit", "Gate 6 + 7 + 8"],
    },
  },
  {
    id: "W4",
    name: "Enterprise harden",
    days: "22–30",
    certify: "M3 isolation + M4 enterprise ops. Horizon M5 listed, not claimed.",
    cells: {
      k: ["Constitutional review of red-team findings"],
      i: ["Named catalogue only — no A3–A5 grants", "Learning candidates, never auto-promoted"],
      p: ["Product 2 through factory", "Portfolio registry of two live products"],
      x: ["Rollback and restore against real deploys"],
      g: ["Command center", "Monitoring + incident + compliance", "RT-001–RT-010", "Gate 9 + Gate 10"],
    },
  },
] as const;

export const DAYS: StrikeDay[] = [
  {
    d: 1,
    wave: "W1",
    focus: "One repo. One constitution. Zero ambiguity.",
    k: "Encode 16 articles as machine-checkable invariants. Repo, CI, constitution package.",
    i: "Intelligence Contract interface only — no provider identity in the kernel.",
    p: "Product Passport schema + closed lifecycleState union.",
    x: "Workspace directory contract. No execution yet.",
    g: "AuditEvent schema and hash-chain spec frozen.",
  },
  {
    d: 2,
    wave: "W1",
    focus: "Schemas before code volume.",
    k: "Domain model, risk classes, identity records.",
    i: "Adapter interface + Claude adapter stub.",
    p: "Discovery intake schema.",
    x: "Worker process contract.",
    g: "Evidence envelope schema.",
  },
  {
    d: 3,
    wave: "W1",
    gate: "Gate 1",
    focus: "Constitutional runtime rejects the unauthorized.",
    k: "Unauthorized actions rejected. Domain model validated.",
    i: "Registry lists named A0/A1/A2 roles — none execute.",
    p: "Passport compiler compiles a fixture.",
    x: "Empty broker health.",
    g: "Audit writes the Gate 1 evidence package.",
  },
  {
    d: 4,
    wave: "W1",
    focus: "Authority is explicit.",
    k: "Authority chains, delegation, revocation.",
    i: "Context packet v1.",
    p: "Requirements engine skeleton.",
    x: "Capability check hooked in the broker.",
    g: "Policy evaluation on every request.",
  },
  {
    d: 5,
    wave: "W1",
    focus: "Capability is scoped. Isolation has a seam.",
    k: "Capability tokens: scope, expiry, audience.",
    i: "Local adapter — second provider seam exists.",
    p: "Blueprint skeleton.",
    x: "Tenant id on every workspace.",
    g: "Isolation Guard interface.",
  },
  {
    d: 6,
    wave: "W1",
    gate: "Gate 2",
    focus: "Trust Kernel is the only path to action.",
    k: "Agent cannot act except through governance. Authorized path succeeds.",
    i: "No agent holds a raw tool.",
    p: "Passport still read-only for agents.",
    x: "Broker refuses unsigned work.",
    g: "Gate 2 evidence package.",
  },
  {
    d: 7,
    wave: "W1",
    focus: "Wave freeze. M0 internal certification.",
    k: "Attack: privilege, expired token, forged authority.",
    i: "Contract tests against the stub adapter.",
    p: "Schema freeze.",
    x: "Workspace isolation dry-run.",
    g: "Daily freeze + M0 dossier.",
  },
  {
    d: 8,
    wave: "W2",
    focus: "Agents may advise. They may not act.",
    k: "Risk class stamped on every proposal.",
    i: "Runtime executes A0 advisory agents.",
    p: "Discovery live.",
    x: "Proposal bus — not an executor.",
    g: "Rate-limit skeleton.",
  },
  {
    d: 9,
    wave: "W2",
    gate: "Gate 3",
    focus: "Identity and capability security hold under attack.",
    k: "Privilege escalation blocked.",
    i: "Forged context rejected.",
    p: "Unauthorized product access blocked.",
    x: "Tenant escape blocked.",
    g: "Expired and forged capability blocked. Gate 3 package.",
  },
  {
    d: 10,
    wave: "W2",
    focus: "Factory writes a passport, not a codebase.",
    k: "Human Owner approval path on the passport.",
    i: "A1 proposal catalogue: Requirements, Architect, Planner.",
    p: "Requirements engine + passport write.",
    x: "No implementation from a draft passport.",
    g: "Evidence of each proposal.",
  },
  {
    d: 11,
    wave: "W2",
    focus: "Idea to plan under governance.",
    k: "Architecture proposal cannot self-approve.",
    i: "Architect Agent A1.",
    p: "Blueprint + architecture + implementation plan.",
    x: "A plan is not a deploy.",
    g: "Plan artifacts hashed into evidence.",
  },
  {
    d: 12,
    wave: "W2",
    gate: "Gate 4",
    focus: "Agent runtime proposes through governance.",
    k: "Governance chain is the only submission path.",
    i: "Agents receive context, generate proposals, submit. No direct execution.",
    p: "Factory states enforced.",
    x: "Broker still closed to unsigned plans.",
    g: "Gate 4 package.",
  },
  {
    d: 13,
    wave: "W2",
    focus: "Product 1 exists as a governed specification.",
    k: "Human Owner approves Product 1 spec.",
    i: "Specialists run only inside Product 1 scope.",
    p: "Supported template (web + API + database) through the factory to APPROVED.",
    x: "Workspace reserved, still empty of product code.",
    g: "Passport + approval in the audit trail.",
  },
  {
    d: 14,
    wave: "W2",
    gate: "Gate 5",
    focus: "Product Factory works. Second provider is real.",
    k: "M2 path proven internally.",
    i: "Second adapter returns a real completion. Routing is still explicit, not a fabric.",
    p: "A product idea produces a governed specification.",
    x: "Ready to accept Gate 5 output.",
    g: "Gate 5 package. Wave freeze.",
  },
  {
    d: 15,
    wave: "W3",
    focus: "Execution is isolated.",
    k: "Capability token required for every run.",
    i: "No agent holds shell, network, or credentials.",
    p: "Product 1 implementation starts under the passport.",
    x: "Execution Broker + isolated workspace + worker.",
    g: "Every run emits an audit event.",
  },
  {
    d: 16,
    wave: "W3",
    gate: "Gate 6",
    focus: "Proposal → governance → isolated execute.",
    k: "Unauthorized execute rejected.",
    i: "Agents still only propose.",
    p: "Product 1 code lands only from approved plans.",
    x: "Controlled execution works.",
    g: "Gate 6 package.",
  },
  {
    d: 17,
    wave: "W3",
    focus: "Execution is not success.",
    k: "Consequential actions require independent verification.",
    i: "Verification Agent at A2 — independent of the executor.",
    p: "Product 1 test plan bound to the passport.",
    x: "Build verification hooked.",
    g: "Test runners + verification engine.",
  },
  {
    d: 18,
    wave: "W3",
    focus: "Evidence precedes trust.",
    k: "E0 is a defect, never a status.",
    i: "Model output is not evidence.",
    p: "Passport records evidence ids.",
    x: "Run artifacts hashed.",
    g: "Evidence store hashing. Append-only audit. Tamper detect.",
  },
  {
    d: 19,
    wave: "W3",
    gate: "Gate 7",
    focus: "Verify, evidence, audit hold.",
    k: "Unverified consequential action is a constitutional violation.",
    i: "A2 verification cannot be the same agent that proposed.",
    p: "Product 1 cannot advance without evidence.",
    x: "Failed verify does not deploy.",
    g: "Gate 7 package.",
  },
  {
    d: 20,
    wave: "W3",
    focus: "Product 1 deploys under governance.",
    k: "Production is a named environment, not a default.",
    i: "No agent deploys.",
    p: "Product 2 factory start (second tenant).",
    x: "Deployment system, environments, post-deploy verify. Product 1 staging.",
    g: "Post-deploy evidence.",
  },
  {
    d: 21,
    wave: "W3",
    gate: "Gate 8",
    focus: "Lifecycle works: build, test, verify, deploy, operate.",
    k: "M1 complete. Factory still M2.",
    i: "Catalogue unchanged.",
    p: "Product 1 operated under the passport. Product 2 in factory.",
    x: "Deployment lifecycle works.",
    g: "Gate 8 package. Wave freeze.",
  },
  {
    d: 22,
    wave: "W4",
    focus: "Two products. Two tenants. One kernel.",
    k: "Portfolio is not a shared memory.",
    i: "Product 2 agents cannot see Product 1 context.",
    p: "Product 2 through the factory.",
    x: "Separate workspaces, separate deploys.",
    g: "Command center shows both. Isolation Guard on.",
  },
  {
    d: 23,
    wave: "W4",
    focus: "Enterprise operations are a product of the kernel, not a slide.",
    k: "Tenant admin and owner controls.",
    i: "No new autonomy grants.",
    p: "Both passports live in the registry.",
    x: "Environment inventory.",
    g: "Monitoring, incident, compliance views.",
  },
  {
    d: 24,
    wave: "W4",
    focus: "Recovery is constitutional.",
    k: "Freeze / rollback / restore are owner actions.",
    i: "Memory candidates only — never auto-promoted (Article 13).",
    p: "Product passports survive restore.",
    x: "Rollback drill against Product 1.",
    g: "Restore drill against fixtures. Incident runbook.",
  },
  {
    d: 25,
    wave: "W4",
    gate: "Gate 9",
    focus: "M3 — Product A cannot access Product B. Both operational.",
    k: "Tenant isolation is an invariant, not a feature flag.",
    i: "Product A agent denied Product B tools, memory, and workspace.",
    p: "Two live products.",
    x: "Two isolated runtimes.",
    g: "Gate 9 isolation proof.",
  },
  {
    d: 26,
    wave: "W4",
    focus: "Red team wave A.",
    k: "RT-001 unauthorized action. RT-002 capability escalation.",
    i: "RT-004 prompt injection.",
    p: "RT-005 malicious repository scoped to Product 1.",
    x: "RT-003 tenant escape.",
    g: "Expected result: reject / block / neutralize. Evidence captured.",
  },
  {
    d: 27,
    wave: "W4",
    focus: "Red team wave B.",
    k: "RT-007 audit tampering.",
    i: "RT-006 secret leakage. RT-008 runaway agent.",
    p: "Passports remain intact under attack.",
    x: "RT-009 failed deployment recovery.",
    g: "RT-010 database corruption restore. Rate limits hold.",
  },
  {
    d: 28,
    wave: "W4",
    focus: "Recovery certification. Learning stays a candidate.",
    k: "Constitutional review of every red-team finding.",
    i: "Verified knowledge candidates only. No self-improvement loop live.",
    p: "Both products still isolated after restore.",
    x: "Rollback and restore succeed on the drill set.",
    g: "Recovery dossier. Zero critical recovery failures.",
  },
  {
    d: 29,
    wave: "W4",
    focus: "M4 ops proof. Close gaps. No new scope.",
    k: "Zero unresolved constitutional violations.",
    i: "M5 seams listed: federation, marketplace, routing fabric, A3+ grants — designed, not live.",
    p: "Completion matrix rows closed or explicitly deferred with owner sign.",
    x: "Monitoring green on both products.",
    g: "Evidence package for Gate 10. Compliance trail complete.",
  },
  {
    d: 30,
    wave: "W4",
    gate: "Gate 10",
    focus: "Certify M4 Enterprise Platform. Horizon remains M5.",
    k: "Articles 1–16 hold under the red-team record.",
    i: "Named agents remain A0 / A1 / A2. Provider independence proven with two adapters.",
    p: "Two products built by the factory, operated under passports.",
    x: "Isolated execution, deploy, rollback, restore — evidenced.",
    g: "Gate 10 package. M4 certified. M5 not claimed.",
  },
];

export const GATES = [
  ["1", "Day 3", "Constitutional runtime works. Unauthorized actions rejected. Domain model validated.", "M0"],
  ["2", "Day 6", "Trust Kernel works. Agent cannot act except through governance. Authorized path succeeds.", "M0"],
  ["3", "Day 9", "Identity and capability security hold: privilege, tenant, expiry, forged token, unauthorized product.", "M0–M1"],
  ["4", "Day 12", "Agent runtime proposes through governance. No direct execution.", "M1"],
  ["5", "Day 14", "Product Factory produces a governed specification. Second provider adapter returns a real completion.", "M2"],
  ["6", "Day 16", "Controlled execution: proposal → governance → isolated workspace.", "M1"],
  ["7", "Day 19", "Execution is not success. Independent verification, evidence, append-only audit.", "M1"],
  ["8", "Day 21", "Lifecycle works: built, tested, verified, deployed, operated under governance.", "M1–M2"],
  ["9", "Day 25", "Product A cannot access Product B. Both operational. Isolation proof is M3.", "M3"],
  ["10", "Day 30", "Red team and constitutional adversarial tests pass. Recovery works. Certified bound is the enforcement spine. M5 is the horizon, not the claim.", "Spine"],
] as const;
